### ISSUE TITLE
Wrong documentation links

### ISSUE THREAD

**Issue by SalahAdDin** [shuup/shuup#1142]
As you can see, documentation is not only wrong indexed but many links are wrong:
![deepinscreenshot_select area_20170627002158](https://user-images.githubusercontent.com/5034215/27560924-a8b3e088-5ace-11e7-88ac-b71b187fb3aa.png)

**Comment by tulimaki** [comment]
Thanks! We will have a look. With quick clicking around could not find anything broken. But like said we will have a closer look.

**Comment by SalahAdDin** [comment]
Thanks!
