### ISSUE TITLE
Initial server configuration blocks django-debugtoolbar performance

### ISSUE THREAD

**Issue by SalahAdDin** [shuup/shuup#1143]
I know, is the normal behavior that `shuup` is under mantained status, but this blocks debug toolbar, it showns a `503` error and can't show any panel.

Why happen this?
![deepinscreenshot20170626231216](https://user-images.githubusercontent.com/5034215/27563321-8c4e9568-5ad9-11e7-971d-064fa8422ead.png)

**Comment by tulimaki** [comment]
Thanks! Yeah "normal behavior". Not sure how much you should be debugging front in the situations when the shop is in maintenance mode. I can't see anything super critical here.

**Comment by chessbr** [comment]
You can probably solve this by just saving the shop name. This error occurs when running the initial migration and then changing the default language in Shuup settings.

**Comment by SalahAdDin** [comment]
Yes, I see. But I think it could show put instead these horrible parameters some like 'unnamed' or 'anonim' shop. Also for security issues.
