### ISSUE TITLE
Can't run "python3 manage.py migrate" due to a missing migration in django-filler

### ISSUE THREAD

**Issue by sergey-pshichenko** [shuup/shuup#1150]
It looks like the required migration dependency from filer package (0007_auto_20161016_1055.py) does not exist in django-filler==1.2.0. However it does exist in version 1.2.7. Unfortunately when I upgraded filer to 1.2.7 it also upgraded some of the packages that filer relies on. Subsequently this broke other things.

Edit: 
0007_auto_20161016_1055.py exists as early as django-filer==1.2.6

**Comment by Pikkupomo** [comment]
How did you install shuup?

**Comment by sergey-pshichenko** [comment]
I used `pip3 install shuup`
Also tried running `pip3 install -r requirements-doc.txt` from shuup package. Just to be sure.

In requirements-doc.txt django-filer is set to version 1.2.0

**Comment by sergey-pshichenko** [comment]
This fixed it:
```pip3 install -U django-filer==1.2.8
pip3 install shuup```
