### ISSUE TITLE
Cryptography 1.7.1 on Fedora

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1152]
Check the possibility of updating package requirement to `cryptography=2.0.1`

Original report from @AbConstruct:

> Hi,
> Is it mandatory to use cryptography=1.7.1
> because of it is failing.I am using Fedora 26.I can install manually cryptography=2.0.1 but not 1.7.1

**Comment by AbConstruct** [comment]
Hi,

I have tried by changing the Cryptography package to 2.0.1 and it is working.

Thanks @Pikkupomo
