### ISSUE TITLE
Cache product prices

### ISSUE THREAD

**Issue by tulimaki** [shuup/shuup#1163]
I believe caching product prices would greatly improve the front performance.

This is also pretty much blocking the product price sorting without custom project specific "hacks".

**Comment by chessbr** [comment]
Yes, I guess we could cache prices but put some flag on the base pricing module to allow this cache. This way we can avoid caching prices for modules that dynamically calculates the price or fetches it from some other source like API etc, then the responsibility is the pricing module to cache it if wanted etc.
