### ISSUE TITLE
Update versions of required third party packages to latest (if possible) 

### ISSUE THREAD

**Issue by tulimaki** [shuup/shuup#1164]

**Comment by chessbr** [comment]
Consider testing dependencies using https://snyk.io to check for security issues. We currently have a lot in our versions, so just to make sure we are at least safe.

**Comment by tulimaki** [comment]
As part of tackling some vulnerability issues at https://github.com/shuup/shuup/pull/1276 I think most of this is now solved. All necessary Python pacakges for 2.0 should pretty much come from that Django 1.11 task.

**Comment by tulimaki** [comment]
https://github.com/shuup/shuup/pull/1282 will include be pretty much rest what comes to Shuup 2.0 I would think.

**Comment by 77cc33** [comment]
django-oscar uses https://pyup.io/ for these purposes, and seems it works very well. Their bot automatically updates dependencies, running tests and create pull request - so all you have, just to merge (if all ok :-) ). 

It's FREE for open sources projects. Looks like really time saver.

![image](https://user-images.githubusercontent.com/2612157/42353457-238106f8-80c9-11e8-8f57-ab4414ca32d1.png)
