### ISSUE TITLE
ShopProduct list view admin supplier column broken

### ISSUE THREAD

**Issue by tulimaki** [shuup/shuup#1170]
The following happens when using the `supplier` column on shop products' list view admin
![image](https://user-images.githubusercontent.com/6592571/34148462-f340895c-e4a9-11e7-89e8-d57ea4833731.png)

All products do have a single supplier set

**Comment by Bayoslav** [comment]
return value is missing on line 357 in admin/utils/picotable.py 
I've added it here:
https://github.com/shuup/shuup/pull/1283
