### ISSUE TITLE
GDPR features for shuup

### ISSUE THREAD

**Issue by finmaster19** [shuup/shuup#1187]
This General Data Protection Regulation (GDPR) will takes effect in May. This regulation touches all companies processing data of EU residents which means that maybe shuup should have built in features to address these requirements? Here is listed at least few features which would address this new regulation:
- User should be able to export all the data collected about him/her
- User should be able to anonymize his/her data in the database so it cannot be linked to the person anymore

We were thinking about this with @suutari-ai that we could implement these two features into shuup inside `shuup.front.apps...` folder so they could be pluggable to projects which requires these features. Maybe these features should be own apps and they would provide `customer_dashboard_items` objects where user could do the wanted actions whenever they want.

**Comment by tulimaki** [comment]
See the [here](https://github.com/shuup/shuup/tree/master/shuup/gdpr)
