### ISSUE TITLE
New Item button doesnt shows in apps

### ISSUE THREAD

**Issue by soulilya** [shuup/shuup#1197]
Hallo! I try to add new plugin for HTML content snippets. But when i came on page with list items but there is no button New Item in right top corner.

**Comment by Pikkupomo** [comment]
Hi @soulilya can you give detailed information what were you trying to do and how?  are you using the existing pages and templates? If so, do you have placeholders for the extra content set in the template?

**Comment by soulilya** [comment]
Hallo, i figure out in my problem. Error was not so obvious.Its problem in django templates i think. Sadly, they return no traceback error, just context doent render.
