### ISSUE TITLE
New tab for categories provides

### ISSUE THREAD

**Issue by soulilya** [shuup/shuup#1206]
Hallo! I try to add new tab for product. But, there is no new tab. I follow this instruction:
http://shuup.readthedocs.io/en/latest/howto/new_tab.html

My models.py
`from django.db import models
from parler.models import TranslatableModel, TranslatedFields
from shuup.core.models._products import Product
from django.utils.translation import ugettext_lazy as _

class ExtendedProductAdmin(TranslatableModel):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)

    extended_translations = TranslatedFields(
        ingridients=models.TextField(
            blank=True, verbose_name=_('ingridients'),
            help_text=_(
                "Ingridients list in product."
            )
        ),
    )`

my forms.py
`from django import forms
from django.utils.translation import ugettext_lazy as _
from shuup.admin.forms.widgets import TextEditorWidget
from .models import ExtendedProductAdmin
from shuup.utils.multilanguage_model_form import MultiLanguageModelForm

class ExtendedProductAdminForm(MultiLanguageModelForm):
    class Meta:
        model = ExtendedProductAdmin
        fields = ("ingridients",)
        widgets = {
             "ingridients":TextEditorWidget(),
         }
`

my views.py
`from django.shortcuts import render
from .forms import ExtendedProductAdminForm
from shuup.admin.form_part import FormPart, TemplatedFormDef

class ExtendedProductDetailsFormPart(FormPart):
    priority = 9
    name = "extended_product_admin_form_part"
    form = ExtendedProductAdminForm

    def get_form_defs(self):

        yield TemplatedFormDef(
            name=self.name,
            form_class=self.form,
            template_name="shuup/admin/products/extended_product_admin_form.jinja",
            required=False
        )`

my template.jinja

`{% from "shuup/admin/macros/general.jinja" import content_block %}
{% set magic_form = form["category_example_form"] %}

{% call content_block(_("Force"), icon="fa-magic") %}
    {{ bs3.render(magic_form) }}
{% endcall %}`

my __init__.py

`from shuup.apps import AppConfig

class ExtendedProductAdminFormConfig(AppConfig):
    name = 'extended_product_admin_form'
    verbose_name = "Extended Product Details"
    label = 'extended_product_admin_form'

    provides ={
        'admin_product_form_part':[
            'shuup.themes.vegetable.plugins.extended_product_admin_form.views.ExtendedProductDetailsFormPart'
        ],
    }
    `

**Comment by chessbr** [comment]
Hi @soulilya 
No errors on console? Is you app inside `INSTALLED_APPS` settings?

**Comment by soulilya** [comment]
Hi, thanks for reply. Need your help.

I figure out, i add this string in init.py and tab displays normally.

default_app_config  = "shuup.themes.vegetable.plugins.extended_product_admin_form.ExtendedProductAdminAppConfig"
I have another question in this context. How i can save formpart one to one relation?

I need save product form and my custom form in new tab.

class CustomProductFormSet ( forms . BaseInlineFormSet ):
def __init__ ( self ,  * args ,  ** kwargs ):
kwargs.pop( "empty_permitted" )
super (CustomProductFormSet,  self ). __init__ ( * args,  ** kwargs)
class ExtendedProductDetailsFormPart ( FormPart ):
priority  = 0
name  = "extended_product_admin_form_part"
formset  = forms.inlineformset_factory(
Product,
ExtendedProductAdmin,
form = ExtendedProductAdminForm,
formset = CustomProductFormSet 
)
def get_form_defs ( self ):
yield TemplatedFormDef(
name = self .name,
form_class = self .formset,
template_name = "shuup/extended_product_admin_form/admin/extended_product_admin_form.jinja" ,
required = False
)
Form saves, but new field form is empty

**Comment by soulilya** [comment]
Prev question i find out, thanks. Very good system. Will be django 1.11 based?


>Понедельник,  5 марта 2018, 19:12 +03:00 от Christian Hess <notifications@github.com>:
>
>Hi  @soulilya
>No errors on console? Is you app inside INSTALLED_APPS settings?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


______________________
Разаработка и продвижение сайтов
http://site-buy.org

**Comment by chessbr** [comment]
Yes, that is on the way! :smile:

**Comment by soulilya** [comment]
And some quetions about system itself.

1.  I want to create multishop. Each shop must have separated themes and doimain names, but one database and filesystem.
Its possible?

2. Can you provide example of external payment sevice ?

**Comment by Pikkupomo** [comment]
Closing issue as per original authors request.
