### ISSUE TITLE
Stuck on template selection in admin wizard

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1214]
After a clean installation of a simple shop, the wizard shows the theme selection pane but there is no way to continue. When clicking next nothing happens.

![image](https://user-images.githubusercontent.com/8770370/37846489-82c3df1a-2eac-11e8-95ec-47cd3ba78ddc.png)

Change this to skip this step if there is no theme available for selection.

**Comment by soulilya** [comment]
just renew page

**Comment by tulimaki** [comment]
This is about the classic gray missing stylesheet previews and the bug in this is fixed in https://github.com/shuup/shuup/commit/f3ebc1bb8f7ac53af4b15d019bcbff4d78169e91.

We are happy to accept PR for actual previews for this theme selection.
