### ISSUE TITLE
Picotable clear selections for mass actions is not that easy

### ISSUE THREAD

**Issue by tulimaki** [shuup/shuup#1244]
I think after successful action all selections should be cleared.

**Comment by maximlion** [comment]
This bar pops up when you try to do a massive action in picotable. If you press "confirm" the selections are cleared. 
![screenshot from 2018-08-21 21-51-22](https://user-images.githubusercontent.com/40273438/44425682-d6a5e180-a58c-11e8-8595-307a61a297cc.png)
I think this should be closed.
