### ISSUE TITLE
Product shouldn't have stock behavior

### ISSUE THREAD

**Issue by tulimaki** [shuup/shuup#1249]
I think supplier alone should define whether product is available stock wise. The supplier also already have "stock_managed" attribute and it would be wise to use that to determine stocking related matters. Maybe supplier "stock managed" should be one of those protected attributes since after there is orders and shipments changing this would cause unnecessary complexity.

This is not currently a huge issue, but improve the logic around stocks.

Let me know if you going to pick this up. I have small WIP branch for this going on.

**Comment by tulimaki** [comment]
In progress. Current vision is that we will move all stock related logic towards suppliers as much as possible. So the product stock behavior likely will be removed.

**Comment by chessbr** [comment]
Done here https://github.com/shuup/shuup/pull/1772
