### ISSUE TITLE
Replace Gulp by Webpack in the entire project

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1286]
Enable the web version so the builds can be faster, smarter and more dynamic.

**Comment by tulimaki** [comment]
We will be doing bigger admin overhaul design and UI wise so, might be wise to avoid touching admin as part of this task. The admin overhaul will be started in week or so. I guess there will be some branch for it to follow the progress.

Also as a note now at least the Xtheme resources has dependencies to the admin-app and likely shouldn't have those. This could be handled as part of solving this issue.

**Comment by tulimaki** [comment]
Waiting admin re-design and we should have this completed...
