### ISSUE TITLE
Add support for Django 2.0

### ISSUE THREAD

**Issue by tulimaki** [shuup/shuup#1289]
Main issue with this is `django-filer` which doesn't support 2.0 yet. First issue raised from filer would be `/filer/utils/compatibility.py`, `from django.utils.functional import allow_lazy`.

Some steps before the above becomes problem:
* `from django.core.urlresolvers import reverse` is no more. And instead needs to be imported from `from django.urls import urlresolvers`
* `javascript_catalog` used for translation catalog in front and admin is no more. So we need to fix the `shuup/utils/i18n/javascript_catalog_all`.

Other potential things that need to be addressed:
* Foreign keys have to have `on_delete` defined
* `is_authenticated()`, `is_anonymous()` is no more. I guess here the problem mainly could be to make this in backwards compatible way.

**Comment by iurisilvio** [comment]
The django-filer package already support django 2.

**Comment by chessbr** [comment]
Done
