### ISSUE TITLE
Enable data importer through bundle files

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1298]
Currently, there is no way of importing data with images or other files. An use case would be importing products data from other platforms, which usually contain images, files etc.

Create some maninfest file standard that can be put inside a zip/gzip file describing the contents of the bundle like paths.

**Comment by tulimaki** [comment]
Fixed! See https://github.com/shuup/shuup/commit/ba5d50014e2ea7eba10511d2cd0b870207493bf2.
