### ISSUE TITLE
Xtheme widgets are being cleaned in multishop setup

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1308]
This prevents multiple shops to add a widget in the same placeholder.
To reproduce the error:

1. Create 2 shops
2. Go to shop 1 and in product detail page, add a widget next to the product price placeholder and save
3. Go to shop 2 and add the same widget in the same placeholder and save
4. Go to shop 1 and see that the widget added is gone

**Comment by tulimaki** [comment]
Fix for this is in progress...

**Comment by chessbr** [comment]
Solved in https://github.com/shuup/shuup/pull/1309
