### ISSUE TITLE
Enable tests with migrations for Django 1.9

### ISSUE THREAD

**Issue by tulimaki** [shuup/shuup#1312]
It seems the tests take way too much time and keep getting timeout. Strong suspect for this is the migrations. And maybe https://github.com/shuup/shuup/issues/1165 could help.

Requires more investigations.

**Comment by chessbr** [comment]
I guess support for Django 1.8 and 1.9 will be dropped on next version. I'm not sure if it worth it doing this.

**Comment by chessbr** [comment]
Dropping support for 1.9 soon so nothing to do here
