### ISSUE TITLE
Enable emoji in text fields

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1334]
Errors occur when trying to save emojis in text fields like product description. This should have something related to databases. Make sure we can use them.

**Comment by chessbr** [comment]
Add some documentation to enable them at least like here: http://blog.manbolo.com/2014/03/31/using-emojis-in-django-model-fields

**Comment by tulimaki** [comment]
Not a Shuup issue. And yes the steps in that blog post looks correct.
