### ISSUE TITLE
Admin: Validation errors hidden on other tabs

### ISSUE THREAD

**Issue by suutari-ai** [shuup/shuup#1337]
Shuup Admin seems to have some problems showing the validation errors on some forms if they are on another tab.  This happens at least with Shuup 1.6.4, Django 1.11.14, django-jinja 2.4.1, jinja2 2.8.1, django-boostrap3 9.1.0 (all installed from  PyPI).

To reproduce:
 1. Create empty database and initialize it with `shuup_init` and `createsuperuser`
 2. Log in to Shuup Admin
 3. Select the "Add logo" action from the "Welcome to Shuup" page.
 4. Set a logo and favicon for the shop and click Save.

What happens:
Seems that nothing happens. It's not certain if the shop got saved or not. But by visiting other admin page and coming back, it appears that the shop didn't get saved. Visiting the General page shows that there is a missing "Public name" field which might have caused the error.

What should happen:
The save should redirect to the tab with validation errors and show the validation errors rendered next to each errorneus field.

Side note:

The shop wasn't savable even after filling in the public name. Found out from the console messages that the reason was `Shop 'Default Shop' has no active theme`. This non-field specific error should be rendered to the form too, since otherwise this message is totally invisible for non-developers without a console access.

**Comment by suutari-ai** [comment]
Found out that some part of this issue gets worse when there is the following in settings:
```python
SHUUP_ADDRESS_FIELD_PROPERTIES = {
    "phone": {"required": True},
    "email": {"required": True},
    "postal_code": {"required": True},
    "name_ext": {"widget": forms.HiddenInput()},
}
```

Because then the following errors were reported to browser's developer console:
```
An invalid form control with name='address-name' is not focusable.
An invalid form control with name='address-street' is not focusable.
An invalid form control with name='address-city' is not focusable.
An invalid form control with name='address-country' is not focusable.```
```

**Comment by suutari-ai** [comment]
The tab with errors seems to get selected correctly on Chrome, but not with Firefox.

**Comment by tulimaki** [comment]
Thanks! We have bigger admin updates in progress and when we have those completed we double check this. Just because likely the whole error handling logic will change as part of those admin changes.

**Comment by tulimaki** [comment]
Fixed!
