### ISSUE TITLE
Cache is not bumped correctly for Front product template tags

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1347]
To reproduce, add a highlight plugin that lists only orderable products, load the page and check for the products which are being rendered. Then, make a product unorderable (change visibility). After refreshing the page the product should be gone. Then make the product visible again, it never comes back.

Make sure to test with caches on:
```py
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'shuup'
    }
}
```

### Steps to reproduce
- go to front and see a product there
- go to admin, see make it invisible
- go to front: it shouldn't be there (it is gone)
- go to admin and make it visible
- go to front: still NOT there <=== :bug: 

The issue is probably the context cache that is not bumped when products are saved. They are bumped through this post_save signal https://github.com/shuup/shuup/blob/master/shuup/core/__init__.py#L54-L69 but the instances are bumped, not lists.

As you can see here https://github.com/shuup/shuup/blob/master/shuup/front/template_helpers/general.py#L145 the `item=None` when generating the cache key, this means it is not attached to any product or object. Thus, when product is bumped this cache is not in the same namespace.

We can either make sure to bump the namespace (and make sure to bump only this shop namespace) OR disable the cache for those lists.

**Comment by tulimaki** [comment]
@chessbr shouldn't this work now since we reset the caches between tests?

**Comment by tulimaki** [comment]
In progress...

**Comment by tulimaki** [comment]
Fixed!
