### ISSUE TITLE
Fix unit tests and make them run with pytest-xdist

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1349]
* Configure Travis to install [`pytest-xdist`](https://github.com/pytest-dev/pytest-xdist) and make tests run faster with `-n auto` parameter. You will probably face errors when pytest start to collect unit tests. To pass that make sure to ignore browser tests passing the `--ignore=shuup_tests/browser` to the command.
* Fix unit tests that crashes. Some tests are interfering on others. As `pytest-xdist` will run on separated threads, the order of unit tests is not the same as running in a single thread. One example is if you run this (without pytest-xdist) `py.test --nomigrations shuup_tests/campaigns/test_basket_campaign_admin.py::test_campaign_new_mode_view_formsets shuup_tests/campaigns/test_basket_campaigns.py::test_product_basket_campaigns2`. This exactly order of tests make the last test break. Investigate the reason, that will probably fix the others.

**Comment by tulimaki** [comment]
@chessbr shouldn't this work now since we reset the caches between tests?

**Comment by chessbr** [comment]
No, if you run that command it still breaks

**Comment by chessbr** [comment]
Not really needed
