### ISSUE TITLE
Windows install instructions documents update 

### ISSUE THREAD

**Issue by 77cc33** [shuup/shuup#1356]
Hello,

There is extra steps required to install Shuup for dev on Windows 10, I tried to build docs with Sphinx and send them as PR #1355 , but seems your docs scripts are little bit outdated, so will put instructions here for better days, while I remember how it was and maybe you'll add it later.

P.S.: I have not very good English for writing docs, but hope you can edit it to get something useful. 

**Windows**
If you want to install all requirements just with **pip**, you have to install MS Visual C++ Build Tools as explained in [Python’s wiki](https://wiki.python.org/moin/WindowsCompilers) This way everything will be build automatically on your Windows machine, alternatively you may install failed to build packages from https://www.lfd.uci.edu/~gohlke/pythonlibs/

If you have  **OSError: dlopen() failed to load a library: cairo / cairo-2** error, please carefully follow these [instructions](https://weasyprint.readthedocs.io/en/latest/install.html#windows)

If you still have the same error, be sure that your installed python and GTK run time has the same 32 or 64 bit. It's important.

Error is still there? Try to edit Windows environment PATH, and move GTK Runtime location to the top of the list.

**Comment by tulimaki** [comment]
Really appreciated!

**Comment by tulimaki** [comment]
Will be solved in few minutes after https://github.com/shuup/shuup/pull/1359 is merged. @77cc33 Thanks once again!
