### ISSUE TITLE
Summernote: Add a way to add files from media browser 

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1376]
The problem with the current Summernote implementation is that it adds all images as inline items and it causes pretty much Shuup instances to explode. I tried to tackle this issue by removing the drag and drop support, but it's still present through the normal image addition.

I would like to see a feature in Shuup where admin user could choose an image from Shuup's own media browser and the image would be added into the content in question as `<img src="mediabrowserimage.jpg" />` instead of `src="data:image/..."`. 

If it's not possible to plug in the media browser in this way, at least the image upload should save the image to media browser and construct a properly linked `<img/>` based on that.

**Comment by tulimaki** [comment]
Related: https://github.com/shuup/shuup/commit/8e7f202cb51a75d2dfafc69fb577c4326542438a
