### ISSUE TITLE
Missing "Person Contact" placeholders on category page

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1383]
It seems it's not possible to set content for Person Contacts only. Not sure if this is intended or not, but would make sense to have "Person Contact" as one of the limiting factors there like Company Contact. 

I'm running the latest Shuup master.

**Comment by tulimaki** [comment]
![screen shot 2018-07-16 at 3 17 13 pm](https://user-images.githubusercontent.com/4940349/42786523-741522b2-890b-11e8-98fe-b927171f7787.png)

Here are the placeholders at the category view one for logged in contacts and one for person contacts.

Can you provide more information about the issue. Should work.

**Comment by Pikkupomo** [comment]
Oooh, you have to be in person contact mode to see those. I thought they are always listed there. 

But anyways, now I think I got it, so:

Always show:
* without limitations
* this category only

Depending on your selection (from the separate menu):
* logged in + person contact 
* logged in + company contact
* guest

I know this is the first version and it's really good as a first one, but I guess there should be a way of "distinguish" the changing placeholders in the future.
