### ISSUE TITLE
Placeholder help text looks like normal text

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1384]
When editing page, the placeholder help texts are looking very similar to the content itself. Maybe a minor improvement here would be in place at some point.

![image](https://user-images.githubusercontent.com/2863405/42784021-aa2f3e4a-8902-11e8-8159-74d9d5780d10.png)

**Comment by tulimaki** [comment]
Happy to merge something for this. But not very important since the placeholders shouldn't be reviewed in edit-mode anyways.
