### ISSUE TITLE
XTheme: showing cell width and align

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1385]
This is more an annoyance than an issue, but I guess I could "ticket" it here as it annoys me every time :) 

Showing the *Cell width* and *Cell align* before plugin selection has been made makes no sense as the values won't be persisted over the actual plugin selection.

For example, add new row => Cell Width: half -> plugin: Text -> see popup -> start over with the width.

I suggest we either
* hide the  *Cell width* and *Cell align* until the Plugin has been selected. 
OR
* make cell width and align come before the Plugin

**Comment by tulimaki** [comment]
We will look into this. Likely we will have something for this in near future.
