### ISSUE TITLE
Xtheme: Empty TextPlugin shows string None

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1386]
Steps to reproduce first way:
1) open placeholder
2) add a row, and
3) add a plugin
4) choose Text from the drop down
5) click "publish changes" and accept

Second way:
1) open placeholder
2) add a row, and
3) add a plugin
4) choose Text from the drop down
5) click save plugin
6) click "publish changes" and accept 

These steps cause the following:
![image](https://user-images.githubusercontent.com/2863405/42788498-a8f4b430-8914-11e8-9493-2454ca539651.png)

and when the editing mode is off it shows like this:
![image](https://user-images.githubusercontent.com/2863405/42788508-bbaaa36e-8914-11e8-8d43-6fef0f2f8691.png)

If it's hard to implement validations (I guess it might be for publish at least), the `None` value could be shown as empty string (`""`).

**Comment by tulimaki** [comment]
Will be fixed soon. Of course the merchant has option to not add these empty placeholders. But I guess it is too hard to preview the end result at the moment.

**Comment by tulimaki** [comment]
Fixed!
