### ISSUE TITLE
Need cryptography unpinned/updated

### ISSUE THREAD

**Issue by jonovate** [shuup/shuup#1395]
Hello,

Why is the cryptography module pinned? I do not see any usages.

Anyways, it is pinned to 1.7.1 which is from 2016 and built against old OpenSSL version.
https://cryptography.io/en/latest/faq/#installing-cryptography-with-openssl-0-9-8-or-1-0-0-fails

Crypto module dropped support around 1.9 for old headers and so if you're building addons, etc. with other requirements which have downchain dependencies, they fail.

Setup.py log: https://pastebin.com/LK6pkdzi
Thanks!

**Comment by tulimaki** [comment]
Thanks. This is related to some old issue we had.  And I agree there shouldn't be any reason to pin this dependency.

We will take a closer look and likely we unpin this for the next released version around Wednesday.

**Comment by tulimaki** [comment]
Yes this is in next release (v1.6.8) which happens today.

**Comment by jonovate** [comment]
@tulimaki Any idea why requirements-doc.txt is still pinning an exact version?

**Comment by tulimaki** [comment]
Hi @jonovate.

Updated the latest requirements here https://github.com/shuup/shuup/commit/0f6f50b2e29027508d4ee1bdefab20cec7b550fa.
