### ISSUE TITLE
ContactGroup has no shop

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1402]
Currently, `ContactGroup` has no `Shop` information. 

**Suggestion**
1) Add `shop` fk to `ContactGroup`.
2) Default groups (persons, companies, anonymous) are shared with all shops and the `shop` is `None` for them.
3) `get_default_group` class method only fetches those `ContactGroup`s without shops
4) When saving a new `ContactGroup` save the currently active shop as well. 
5) While adding this, consider moving `get_price_display_options` as it might need the current shop as well

...or something, would appreciate feedback for the idea.

**Comment by tulimaki** [comment]
In progress!

**Comment by tulimaki** [comment]
Done in https://github.com/shuup/shuup/commit/64a4896430402d81411d7fb81f731f9192acfb98.
