### ISSUE TITLE
CDN Usage in Shuup

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1404]
Currently, Shuup has a lot of CDN references. 

In Jinja files alone, we have this amount:
![image](https://user-images.githubusercontent.com/2863405/43160286-94d7b6a2-8f39-11e8-8062-935d484989fc.png)

I think this exposes Shuup installation to unwanted 3rd party problems and could cause Shuup merchants and their support unwanted headache. 

In my opinion, all these resources should be provided locally from Shuup installation to ensure best possible performance for every instance. 

Thoughts?

**Comment by tulimaki** [comment]
Yes makes sense. This should likely wait that all the resource builds are updated to Parcel.

**Comment by maximlion** [comment]
This can be closed.

**Comment by chessbr** [comment]
I guess we have to check admin too

**Comment by tulimaki** [comment]
Yes let's check admin before closing. But let's wait https://github.com/shuup/shuup/pull/1443 first.

**Comment by tulimaki** [comment]
Done!
