### ISSUE TITLE
Contact address is not loaded when making new orders from contacts detail page

### ISSUE THREAD

**Issue by igordavydsson** [shuup/shuup#1432]
When we try to make a new order, the contact's address does not get loaded automatically to this new order. We are sure, that the contact has addresses, since those can actually be seen on the frontend in the "My account" dashboard.

![peek 2018-08-17 12-13](https://user-images.githubusercontent.com/24206160/44258235-0795b780-a217-11e8-954b-b1032437c9a2.gif)

**Comment by maximlion** [comment]
Hi @igordavydsson, I did not manage to reproduce this bug, everything works good for me. What version of shuup are you using?

**Comment by igordavydsson** [comment]
Hey @maximlion , thanks for the reply!
Indeed, it seems that the issue is not present in >=1.6.9
I reported the issue when we were using 1.6.3, but now everything works fine. :)
