### ISSUE TITLE
Product Quantity Step

### ISSUE THREAD

**Issue by kreativedev** [shuup/shuup#1473]
I see this code here https://github.com/shuup/shuup/blob/master/shuup/core/models/_product_shops.py#L465

However, I am unable to find where in the admin or where on a product you are able to set the quantity step value for a decimal product.

**Comment by tulimaki** [comment]
![screen shot 2018-09-10 at 8 38 54 am](https://user-images.githubusercontent.com/4940349/45307964-3a109880-b4d5-11e8-9b9e-85b9df2ee2c3.png)

Quantity step can be found at admin under shop product tab as purchase multiple. As a fallback Shuup defines quantity step from sales unit [here](https://github.com/shuup/shuup/blob/master/shuup/core/models/_units.py#L89).

[Here](https://github.com/shuup/shuup/blob/master/shuup/front/templates/shuup/front/macros/product_ordering.jinja#L136) at the front product detail the quantity step is used with the quantity input.
