### ISSUE TITLE
Admin UI: Tour missing arrow

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1498]
View your storefront is missing an arrow.

![image](https://user-images.githubusercontent.com/2863405/45567678-54b57b00-b80f-11e8-9d43-32d33fea2115.png)

**Comment by TianSc** [comment]
I am sitting with the same problem where the arrow is not showing, Any news if it is still happening or if there is a fix yet?

**Comment by Pikkupomo** [comment]
@TianSc updating shepherd solved the issue on our project.

**Comment by TianSc** [comment]
That is amazing I will get it implimented asap.

Thank you :-)

**Comment by Pikkupomo** [comment]
This has been solved
