### ISSUE TITLE
Admin UI: Scrolling currency dropdown scrolls the entire page

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1502]
This happens when scrolling with scrollwheel 

url: `http://localhost:8000/sa/wizard/?pane_id=general`

![image](https://user-images.githubusercontent.com/2863405/45568955-ff7b6880-b812-11e8-995d-937a08d0e6d4.png)

**Comment by maximlion** [comment]
This I think, is an issue with `select2` itself, which is gonna be replaced soon by normal django select field. Check #1458

**Comment by maximlion** [comment]
This seems to be select2 bug, select2 in admin will soon be replaced by normal django select field.
Check #1458

**Comment by tulimaki** [comment]
Couldn't reproduce. Seems to work perfectly on latest Chrome, Firefox and Safari. Re open if relevant.
