### ISSUE TITLE
Admin UI: Opening product for the first time shows wrong tour

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1506]
First product open (existing product from sample data) of the instance

![image](https://user-images.githubusercontent.com/2863405/45569843-a8c35e00-b815-11e8-8fff-7158e5d32fe8.png)

**Comment by tulimaki** [comment]
Couldn't reproduce this. First time I login to admin I got home tour like expected. Then I started to process wizard. Created some sample products too. Then when I entered product admin I got this tour like I should. Also tested the category tour and that works too.

Also tested that the tour goes away after things happened first time.

Will close now, but let's re-open or re-investigate if something new pops up.
