### ISSUE TITLE
Admin UI: Some content misaligned

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1514]
See below. 

![image](https://user-images.githubusercontent.com/2863405/45573178-897dfe00-b820-11e8-814d-b4d9e53cf53c.png)

compared to
![image](https://user-images.githubusercontent.com/2863405/45573195-9ac70a80-b820-11e8-9b1e-d403caa6269e.png)

Also, in mobile, there is some "oddness":
![image](https://user-images.githubusercontent.com/2863405/45573257-ea0d3b00-b820-11e8-88ed-44b93e447d8c.png)

**Comment by tulimaki** [comment]
https://github.com/shuup/shuup/pull/1527
