### ISSUE TITLE
Improve tours

### ISSUE THREAD

**Issue by tulimaki** [shuup/shuup#1560]
https://github.com/shuup/shuup/blob/master/shuup/admin/views/tour.py#L15 might not work well in multishop instance.

Also make sure that closing tour from "x" also makes it completed.

**Comment by maximlion** [comment]
Tour only shows the search bar and the "View your storefront" when the menu is hidden as well.

**Comment by tulimaki** [comment]
Multishop part still missing. Also tour styles look far from optimal.

**Comment by tulimaki** [comment]
Rounded corners. Buttons should have primary colors. Make sure all tour steps has that close available. Sync the font what we have now in rest of the admin.

![screen shot 2018-10-03 at 9 25 07 am](https://user-images.githubusercontent.com/4940349/46424583-61cad900-c6ee-11e8-9886-1099c7369075.png)

![screen shot 2018-10-03 at 9 26 42 am](https://user-images.githubusercontent.com/4940349/46424604-74dda900-c6ee-11e8-961e-a075faba12ac.png)

For multishop this should take a long way:
````
diff --git a/shuup/admin/views/tour.py b/shuup/admin/views/tour.py
index dbd9d2b3f..20cdc2bd5 100644
--- a/shuup/admin/views/tour.py
+++ b/shuup/admin/views/tour.py
@@ -10,10 +10,11 @@ from django.http.response import JsonResponse
 from django.views.generic import View
 
 from shuup import configuration
+from shuup.admin.shop_provider import get_shop
 
 
 class TourView(View):
     def post(self, request, *args, **kwargs):
         tour_key = request.POST.get("tourKey", "")
-        configuration.set(None, "shuup_%s_tour_complete" % tour_key, True)
+        configuration.set(get_shop(request), "shuup_%s_tour_complete" % tour_key, True)
         return JsonResponse({"success": True})
```
Unit tests needed though. Also write small Django shell-script to enable all tours that has been "completed" without shop.
