### ISSUE TITLE
XTheme: Missing placeholder variations

### ISSUE THREAD

**Issue by Pikkupomo** [shuup/shuup#1566]
in Simple CMS it's now possible to add quite a few variations of a different kind of content. 

However, the following are missing:
1) "show this content for this page and registered only"
2) "show this content for this page and anonymous only"

So, I guess (at least) the simple cms static pages should have these options. Maybe others as well if it's easy to add.

**Comment by tulimaki** [comment]
https://github.com/shuup/shuup-xtheme-extra-layouts
