### ISSUE TITLE
Admin: it is impossible to uncheck Reports from permission groups

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1568]
![image](https://user-images.githubusercontent.com/8770370/46307692-fe299a00-c58d-11e8-9dcd-f202f7cab40d.png)
Even if I uncheck and save, that will still be checked

**Comment by tulimaki** [comment]
This is due that we only support permissions related to Django models. And reports module does not have models which makes the permissions always on.

I guess first step is to filter out these that can't be toggled (quick). And second step is to introduce Shuup option to add custom permissions (likely bigger task).

**Comment by chessbr** [comment]
Fixed
