### ISSUE TITLE
Fix XTheme form styles

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1606]
The form table stretches too much when fields has long values

![image](https://user-images.githubusercontent.com/8770370/46870971-8289e180-ce06-11e8-85df-29f2ea66e5ff.png)

Consider updating to bootstrap 4?

**Comment by Pikkupomo** [comment]
I suggest we do it like this

https://github.com/shuup/shuup/compare/master...Pikkupomo:xtheme-proto?expand=1

![image](https://user-images.githubusercontent.com/2863405/47533144-7a4e8f00-d867-11e8-8faa-27fbb8e320a5.png)

1) Minimize option
2) close option
3) popup opens directly when clicking the area
4) no left bar anymore

Thoughts?
