### ISSUE TITLE
Marketplace with Shuup

### ISSUE THREAD

**Issue by dansamara** [shuup/shuup#1655]
Hello!

How on the Shuup system can I implement the marketplace: many vendors (shops) and one showcase with goods from all shops and one category tree for all shops? And is it possible at all?

Based on reading the code, when displaying products, categories and other components, we always need to determine the current store.
However, categories and products has many to many relationships with stores, which allows me to create products and categories that are available in different stores. I created several relation rows directly in the database (tables: shopproduct and shopproduct_supplier) for products and suppliers and got the expected behavior - goods from different stores are displayed on the front for _main_ (default) shop. So, when on save a product in any store, we can automatically add a link to the _main_ store and get all products from all stores on the front.

Is this the correct way for Shuup? 
There are other ways to solve the problem of creating a marketplace at Shuup?

**Comment by tulimaki** [comment]
Hi!

We are currently creating a demo for precisely this scenario. As we are a little busy with this, I would like to explain you all this a little later. The demo should be out Friday morning PST time. Long story short is that the suppliers are the key here, but will require some business decisions and not everything is available out of the box at the open source core.

In case there is some sort of delay with that demo I will anyways get back to this around Friday.

**Comment by dansamara** [comment]
Thanks for the quick response!

Yes, I see that in recent releases a lot of work has been done in parts of working with suppliers. I still do not understand the architecture of Shuup and do not know why suppliers are so important. I can assume that this is due to warehouses and delivery.

I am looking forward to the demo and will definitely test it as soon as it is released.

**Comment by Pikkupomo** [comment]
@dansamara to get access to demo once it's up an running, please send a request to support@shuup.com

**Comment by saurabh1920** [comment]
Hi, do we have updates on this?

How can I enable multi vendor support?

**Comment by barnwell** [comment]
> Hi, do we have updates on this?
> 
> How can I enable multi vendor support?

@tulimaki I'm also interested in this. Any updates?

**Comment by dpnkrg** [comment]
Does Shupp open source provide multi-vendor support?
