### ISSUE TITLE
Can't find manage.py file anywhere

### ISSUE THREAD

**Issue by mdnur89** [shuup/shuup#1662]
Hi there, I've just installed shuup from pip and cloned the repo hence installed all requirements plus node modules too. But after I looked for the manage.py file but I can't find it. Did I miss something.

**Comment by maximlion** [comment]
Hi @mdnur89, we extended manage.py to shuup_workbench directory, there you can find all the necessary settings. 
To start a server just run `python shuup_workbench runserver`,
to migrate `python shuup_workbench migrate` etc.

**Comment by chessbr** [comment]
Hi @mdnur89 !
Shuup is a Django **app**, not a **project**, it means it can be installed in existing Django projects. That is why it doesn't include a `manage.py`.

To use it in production, you should create a Django project and then add `shuup` and all its addons to your **INSTALLED_APPS**. Shuup also has many settings to configure.

In the other hand, we have `shuup_workbench` module inside the repository. It is a Django project which we use to develop and test.

You can use it to test Shuup. Instead of running `python manage.py migrate` you should run `python -m shuup_workbench migrate`. All other management commands (runserver, shuup_init and createsuperuser) follow the same command.

If you create a new Django project, then I suggest you to copy/paste the `base_settings.py` we have in `shuup_workbench` module and change according to you project specs :smiley: 

Check https://github.com/shuup/shuup/blob/master/shuup_workbench/settings/base_settings.py

Follow this if you want to create a project from the scratch: https://shuup.readthedocs.io/en/latest/howto/getting_started.html
And this to test Shuup or develop with Shuup:
https://shuup.readthedocs.io/en/latest/howto/getting_started_dev.html

**Comment by mdnur89** [comment]
Hey there sir, oh is it now. Kinda thought that when I invoked ./pip install shuup then after it finished I expected to see the folders but none as it's a package, dumb of me there.

So all I have to do is invoke the django-admin.py startproject and I'm literally underway .

Lemme take a look at those docs you've linked. Because all I want it to make an ecom store that sells tshirts, caps and hoodie's and that's all. Nothing complicated. Hopefully I can easily achieve it with you guys.

**Comment by mdnur89** [comment]
@chessbr Say I don't want to start from scratch, and I want to make edits like logos and a couple of other things as my goal is to make a site that sells only three items only. Can I achieve that using the workbench as a starting point?

**Comment by chessbr** [comment]
@mdnur89 Hey, the "start from scratch" is not hard. I created a project template so you can understand:
https://github.com/chessbr/shuup-project-template

Just clone/copy the repo and change it accordingly. :beer:

**Comment by mdnur89** [comment]
@chessbr Okay man, lemme delve into this one aswel. On the other hand, what happened is I started a project inside the clone of shuup where there was a manage.py which I ran the migrate command and the shuup_init command and it sent me the landing page and in CMD it's saying xtheme.middleware error shop 'default shop' has no active theme.

**Comment by chessbr** [comment]
@mdnur89 you should access the adin http://localhost:8000/sa/ (or what ever is your server url) and select a theme for your shop.

**Comment by mdnur89** [comment]
@chessbr Already reached the wizard after a few failures but seems fine. I wanted to know how much of this can be customized and is it deployable?

**Comment by chessbr** [comment]
Hi @mdnur89 
Shuup is almost entirely customizable at front (templates, code injection, etc). You can create a new template and change whatever you want. :smile:

**Comment by mdnur89** [comment]
@chessbr Hi there sir, is it almost infinitely customizable?, as the front is the one that matters. Sorry for asking but how would one create a template from shuup then edit whatever is needed?

**Comment by chessbr** [comment]
You can check here the default Shuup's theme: https://github.com/shuup/shuup/tree/master/shuup/themes/classic_gray

And the docs how to design templates: https://shuup.readthedocs.io/en/latest/ref/templates.html

**Comment by mdnur89** [comment]
@chessbr Hey there, quick question. Are Jinja files in the templates modifiable because to be honest I didn't think jinja2 was actually a thing. How would one go about modifying jinja files.

**Comment by chessbr** [comment]
Please, take a moment to read our merchant documentation:
https://shuup-guide.readthedocs.io/en/latest/

You can find out more about editing a page here: https://shuup-guide.readthedocs.io/en/latest/using-themes.html#editing-a-page

**Comment by mdnur89** [comment]
@chessbr Is it true that I can only get hosted by shuup and nowhere else like heroku and such. If so I read about the white label license, what is that all about .

**Comment by mdnur89** [comment]
@chessbr Hey there, my storefront is missing icons for the search-field, language-field and cart-field. Everything installed properly, esp the gtk-2 and gtk-3 dependencies aswel. Please advise.

**Comment by chessbr** [comment]
@mdnur89 icons are fetched from fontawesome and are included in the distribution package. Can you take a SS so I can see where is the error? Could you also try cleaning the browser cache and trying again?

**Comment by chessbr** [comment]
@mdnur89 Please, take a look at the license we use to distribute Shuup Open Source: https://opensource.org/licenses/OSL-3.0. There is no limitations how the open source installation is hosted. One more thing about the icons: maybe the browser console errors has the answer.

**Comment by mdnur89** [comment]
@chessbr Hi there, sorry for the late response but are those what you requested as thats what i was talking about.

![missing_icons1](https://user-images.githubusercontent.com/36082948/50024954-a6c39380-ffec-11e8-9b35-100a7f59ef51.PNG)
![missing_icons2](https://user-images.githubusercontent.com/36082948/50024955-a6c39380-ffec-11e8-9dc1-87ed04c06746.PNG)

**Comment by chessbr** [comment]
@mdnur89 have you done what I've suggested above?

**Comment by mdnur89** [comment]
@chessbr About the hosting thing it's only that i was reading up on that on some articles around and the page showing the licenses on the shuup website all bring back 404 errors and i am sorry i am a very curious cat and i tend to want to investigate a lot.

**Comment by mdnur89** [comment]
@chessbr Yeah i tried clearing the cache, killed the browser and machine but nothing, i'm getting those annoying box placeholders.

**Comment by mdnur89** [comment]
@chessbr Oh, the console error of the browser....
![capture](https://user-images.githubusercontent.com/36082948/50025963-eb046300-ffef-11e8-859d-467a8b239055.PNG)

**Comment by chessbr** [comment]
@mdnur89 try running `python setup.py build_resources` Then restart your local server and force refresh the browser.
