### ISSUE TITLE
Is Shuup in Active Development?

### ISSUE THREAD

**Issue by billiemead** [shuup/shuup#1692]
I ask because you cannot signup at your website to join the community?  The link to register (along with Lost Password links etc.) all are broken.

Also, there are numerous problems with what should be a dead-simple install to give the populated demo a  go... (workbench)

1. The Welcome page at http://127.0.0.1:8000/ is looking for a style sheet at http://127.0.0.1:8000/static/shuup/front/css/style.css but no love... where is this hanged so I can set the correct path?

2. Where does the admin login? Attached is the screenshot of all that is displayed and there is no link to the admin dashboard and no reference to it in the documentation.... 
![screencapture-127-0-0-1-8000-2019-01-02-12_14_24](https://user-images.githubusercontent.com/8992422/50603348-38098580-0e88-11e9-8913-5eaf5f0bb9ef.png)

We'd love to try Shuup open source to get a feel if the paid version is what we are looking for to set up our shop/site but need some guidance getting past these few issues.

Cheers and Happy New Year!

**Comment by tulimaki** [comment]
Yes it is.

We are working on the shuup.com website at the moment and the community login should be temporary closed.

For the workbench problems:
1. Maybe you didn't generate the static resources while setting up workbench. [Here is how you can generate static resources.](https://shuup.readthedocs.io/en/latest/howto/getting_started_dev.html#building-resources)
2. By default admin can be found under http://127.0.0.1:8000/sa. URLs are defined [here](https://github.com/shuup/shuup/blob/master/shuup_workbench/urls.py#L12).

Thank you for your feedback. We will improve this. Also there will be Django-project template for Shuup incoming to make it fast and easy to setup new Shuup projects.

**Comment by billiemead** [comment]
Hi and thanks for the reply. I didnt see the automatic notification until just now as it went into my spam folder. But I really appreciate you taking the time to reply and I will try again this evening!

**Comment by tulimaki** [comment]
@billiemead no problem! We created [this](https://github.com/shuup/shuup-project-template) Django project template for making basic Shuup setups easier.

Also if you need more information about Shuup you can contact us at support@shuup.com. We try to keep it development/issues only here and at [Gitter](https://gitter.im/shuup/shuup).
