### ISSUE TITLE
OperationalError: no such table: main.shuup_contact__old

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1730]
This happens when running `shuup_init` management command.

This is related to https://code.djangoproject.com/ticket/29182
It was fixed in Django in https://github.com/django/django/pull/10733 but not available in 1.11 just yet.

A temp fix is to downgrade version of the SQLite to some version below 3.26.

**Comment by tulimaki** [comment]
For macOS and brew use `brew upgrade sqlite` (sqlite version should be >3.26 after this. If the error persist make sure your Django version is >1.11.18.

**Comment by tulimaki** [comment]
https://media.giphy.com/media/l4HnXMxrPGGXmDHW0/giphy.gif

At least with Python 3.7.1 using sqlite 3.27.1 causes not so random segmentation fault.

Downgrade back to older sqlite helped here is link to get [sqlite@3.24.0](https://raw.githubusercontent.com/Homebrew/homebrew-core/f3894da8d5a95c3a677595c0d814ea73ac146c84/Formula/sqlite.rb)

**Comment by jyoost** [comment]
on linux: check permissions on .sqlite directory. on my system it was owned by root and only writeable by root. i did sudo chmod a+w .sqlite

All is fine!
