### ISSUE TITLE
Admin: fix bug in product status text help text

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1737]
Looks like some quotes issue in HTML:

![image](https://user-images.githubusercontent.com/8770370/52476761-d626f480-2b86-11e9-9bbd-e63556ae08b8.png)
![image](https://user-images.githubusercontent.com/8770370/52476814-0373a280-2b87-11e9-810c-e6d5de22e979.png)

**Comment by maximlion** [comment]
This seems to have been fixed.

**Comment by wardal** [comment]
> This seems to have been fixed.

The same for me.
