### ISSUE TITLE
Out of date Dependencies

### ISSUE THREAD

**Issue by jonovate** [shuup/shuup#1741]
Ran requirements through PyUP.

babel | ==2.5.3 | 2.6.0 | outdated | Python 3 | Permissive | PR
certifi | ==2018.10.15 | 2018.11.29 | outdated | Python 3 | Weak Copyleft | PR
cryptography | ==2.4.1 | 2.5 | outdated | Python 3 | Permissive | PR
django-bootstrap3 | ==9.1.0 | 11.0.0 | outdated | Python 3 | Permissive | PR
django-countries | ==5.2 | 5.3.2 | outdated | Python 3 | Permissive | PR
django-enumfields | ==0.9.0 | 1.0.0 | outdated | Python 3 | Permissive | PR
django-filer | ==1.4.0 | 1.4.4 | outdated | Python 3 | Permissive | PR
django-filter | ==1.1.0 | 2.1.0 | outdated | Python 3 | Permissive | PR
django-js-asset | ==1.1.0 | 1.2.1 | outdated | Python 3 | Permissive | PR
django-parler-rest | ==1.4.2 | 2.0 | outdated | Python 3 | Permissive | PR
django-registration-redux | ==1.8 | 2.5 | outdated | Python 3 | Permissive | PR
django-rest-swagger | ==2.1.2 | 2.2.0 | outdated | Python 3 | Permissive | PR
django-reversion | ==2.0.13 | 3.0.3 | outdated | Python 3 | Permissive | PR
django-timezone-field | ==2.1 | 3.0 | outdated | Python 3 | Permissive | PR
django | ==1.11.16 | 2.1.5 | outdated | Python 3 | Permissive | PR
djangorestframework | ==3.5.4 | 3.9.1 | outdated | Python 3 | Permissive | PR
easy-thumbnails | ==2.5 | 2.6 | outdated | Python 3 | Permissive | PR
entrypoints | ==0.2.3 | 0.3 | outdated | Python 3 | Permissive | PR
factory-boy | ==2.7.0 | 2.11.1 | outdated | Python 3 | Permissive | PR
fake-factory | ==0.5.3 | 9999.9.9 | outdated | Python 3 | Permissive | PR
idna | ==2.7 | 2.8 | outdated | Python 3 | Permissive | PR
jinja2 | ==2.8.1 | 2.10 | outdated | Python 3 | Permissive | PR
keyring | ==16.1.0 | 17.1.1 | outdated | Python 3 | Permissive | PR
keyrings.alt | ==3.1 | 3.1.1 | outdated | Python 3 | Permissive | PR
lxml | ==4.2.1 | 4.3.1 | outdated | Python 3 | Permissive | PR
markdown | ==2.6.11 | 3.0.1 | outdated | Python 3 | Permissive | PR
openpyxl | ==2.5.10 | 2.6.0 | outdated | Python 3 | Permissive | PR
pillow | ==5.3.0 | 5.4.1 | outdated | Python 3 | Unknown | PR
pygments | ==2.2.0 | 2.3.1 | outdated | Python 3 | Permissive | PR
pyjwt | ==1.6.4 | 1.7.1 | outdated | Python 3 | Permissive | PR
python-dateutil | ==2.7.5 | 2.8.0 | outdated | Python 3 | Permissive | PR
pytz | ==2018.7 | 2018.9 | outdated | Python 3 | Permissive | PR
requests | ==2.20.1 | 2.21.0 | outdated | Python 3 | Permissive | PR
secretstorage | ==2.3.1 | 3.1.1 | outdated | Python 3 | Permissive | PR
six | ==1.11.0 | 1.12.0 | outdated | Python 3 | Permissive | PR
sphinx | ==1.5.6 | 1.8.4 | outdated | Python 3 | Permissive | PR
xlrd | ==1.1.0 | 1.2.0 | outdated | Python 3 | Permissive | PR

In addition, pytoml is deprecated and has been replaced by toml.

Anything that we shouldn't update?

**Comment by tulimaki** [comment]
Updated the latest requirements here [0f6f50b](https://github.com/shuup/shuup/commit/0f6f50b2e29027508d4ee1bdefab20cec7b550fa).

Not sure if these requirements should be used much since for development you should likely just use `pip install -e .[everything]` and for projects you should run Shuup through Django-project for example like here https://github.com/shuup/shuup-project-template.

But will be keep these updates as part of the new releases.

**Comment by jonovate** [comment]
@tulimaki I see you're still using pytoml instead of toml.

**Comment by tulimaki** [comment]
Yes pytoml is requirement for the xtheme-app and we haven't had reason to change that to toml just yet. Please let me know if you have some issue with this and we will reconsider.

**Comment by jonovate** [comment]
No reason on the pytoml, just trying to see less warnings :).

But, any chance you can upgrade lxml to something newer??  The pinned
version has Windows issues during the pip setup step -- it appears 4.3.2
installs cleanly for example.

**Comment by tulimaki** [comment]
lxml is locked to that version because we had some issue while running tests against the newer version. Should be safe to use newer version though (the issue might be in our test) but likely you will receive some warning.

I will allocate some resource to double check if we can finally release the lxml version lock. And maybe while at it take a quick look into that toml package.

**Comment by jonovate** [comment]
Ok, if you can even try just to 4.2.5 that would be great.  Per
https://stackoverflow.com/a/53112077

**Comment by tulimaki** [comment]
@jonovate thanks for your feedback. We will address this before we do the next 1.9.1 release.

And if you have spare time we would always appreciate some feedback about Shuup and maybe some tips where to improve. Doesn't hurt to include some information how you found us or what kind of eCommerce project you are working on. This kind of stuff you can share here or just send quick email to support@shuup.com. Maybe we can even help you with something.
