### ISSUE TITLE
Powered by Shuup

### ISSUE THREAD

**Issue by mdnur89** [shuup/shuup#1749]
I wanted to ask, is the Powered by Shuup text/link removable... As in can I block it out so it won't appear at all.
Is this possible or it's somewhat hardcoded.

**Comment by tulimaki** [comment]
It is not hardcoded and is coming from here in [default theme](https://github.com/shuup/shuup/blob/master/shuup/front/template_helpers/general.py#L433).

Also you have all kinds of options to override the footer macro/template from your Django-project.

**Comment by mdnur89** [comment]
@tulimaki thank you for the guidance, very much appreciated.
