### ISSUE TITLE
Unknown command: 'shuup_populate_mock'. Type '__main__.py help' for usage.

### ISSUE THREAD

**Issue by saifulazad** [shuup/shuup#1755]
When running `python -m shuup_workbench shuup_populate_mock --with-superuser=admin` in terminal it says - **Unknown command: 'shuup_populate_mock'. Type '__main__.py help' for usage.**

**Comment by chessbr** [comment]
@saifulazad Hi!
I would say that `shuup` is not installed in your virtualenv.
If you are running using the source code, have you changed the `base_settings.py` ? If so, `shuup.testing` should be in `INSTALLED_APPS` to this command be available.

**Comment by saifulazad** [comment]
Hi @chessbr ,
Thanks. It is working

**Comment by ljcljc** [comment]
Hi, I am having the same problem. What do I need to change about "base_settings.py"? I am running source code.

**Comment by chessbr** [comment]
@ljcljc make sure Shuup is installed in your virtualenv: `pip install -e /path/to/shuup/source`
