### ISSUE TITLE
 cannot run python setup.py build_resources

### ISSUE THREAD

**Issue by saikirubamj** [shuup/shuup#1767]
(shuup-demo) ewall@ewall-All-Series:~/Desktop/shuup$ sudo python setup.py build_resources
running build_resources
*** (1/14) Building: ./shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr

> deasync@0.1.14 install /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync
> node ./build.js

`linux-x64-node-11` exists; testing
Problem with the binary; manual build incoming
stdout=
err=Error: Command failed: /usr/local/bin/node quick-test.js
/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/build/deasync.node
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/build/Debug/deasync.node
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/build/Release/deasync.node
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/out/Debug/deasync.node
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/Debug/deasync.node
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/out/Release/deasync.node
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/Release/deasync.node
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/build/default/deasync.node
 → /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/compiled/11.10.0/linux/x64/deasync.node
    at bindings (/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/index.js:30:31)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/quick-test.js:1:82)

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync/build'
gyp ERR! System Linux 3.13.0-165-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules/deasync
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.14 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ewall/.npm/_logs/2019-02-28T12_54_38_196Z-debug.log
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    cmdclass=utils.COMMANDS
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/commands.py", line 83, in run
    resource_building.build_resources(opts)
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/resource_building.py", line 44, in build_resources
    builder.build_all()
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/resource_building.py", line 65, in build_all
    self.build_dirs(package_json_dirs)
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/resource_building.py", line 78, in build_dirs
    self.build(dir)
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/resource_building.py", line 89, in build
    subprocess.check_call(self.install_command, cwd=dir, env=self.env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1

**Comment by chessbr** [comment]
You should never run that command with `sudo`.
Remove `node_modules` and run that command again. Make sure to have virtualenv enabled.

https://shuup.readthedocs.io/en/latest/howto/getting_started_dev.html#building-resources

**Comment by saikirubamj** [comment]
**I tried without sudo still throwing an error**

(shuup-demo) ewall@ewall-All-Series:~/Desktop/shuup$ python setup.py build_resources
running build_resources
*** (1/14) Building: ./shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr
npm ERR! path /home/ewall/.npm/_logs/2019-02-28T11_52_33_008Z-debug.log
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/home/ewall/.npm/_logs/2019-02-28T11_52_33_008Z-debug.log'
npm ERR!     at Object.unlinkSync (fs.js:972:3)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:333:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at Glob.emit (events.js:197:13)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12
npm ERR!     at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)
npm ERR!     at FSReqCallback.args [as oncomplete] (fs.js:145:20)
npm ERR!  { Error: EACCES: permission denied, unlink '/home/ewall/.npm/_logs/2019-02-28T11_52_33_008Z-debug.log'
npm ERR!     at Object.unlinkSync (fs.js:972:3)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:333:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at Glob.emit (events.js:197:13)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12
npm ERR!     at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)
npm ERR!     at FSReqCallback.args [as oncomplete] (fs.js:145:20)
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, unlink '/home/ewall/.npm/_logs/2019-02-28T11_52_33_008Z-debug.log'\n    at Object.unlinkSync (fs.js:972:3)\n    at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)\n    at /usr/local/lib/node_modules/npm/lib/npm.js:333:20\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)\n    at Glob.emit (events.js:197:13)\n    at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)\n    at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)\n    at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)\n    at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17\n    at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)\n    at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12\n    at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)\n    at FSReqCallback.args [as oncomplete] (fs.js:145:20)",
npm ERR!   errno: -13,
npm ERR!   syscall: 'unlink',
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/ewall/.npm/_logs/2019-02-28T11_52_33_008Z-debug.log' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm WARN checkPermissions Missing write access to /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules
npm ERR! path /home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules']
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, access '/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path:
npm ERR!    '/home/ewall/Desktop/shuup/shuup-demo/lib/python2.7/site-packages/shuup-1.9.1b4.post0.dev1+g1028b3f.dirty-py2.7.egg/shuup/gdpr/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    cmdclass=utils.COMMANDS
  File "/home/ewall/Desktop/shuup/shuup-demo/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/commands.py", line 83, in run
    resource_building.build_resources(opts)
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/resource_building.py", line 44, in build_resources
    builder.build_all()
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/resource_building.py", line 65, in build_all
    self.build_dirs(package_json_dirs)
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/resource_building.py", line 78, in build_dirs
    self.build(dir)
  File "/home/ewall/Desktop/shuup/shuup_setup_utils/resource_building.py", line 89, in build
    subprocess.check_call(self.install_command, cwd=dir, env=self.env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 243

**Comment by tulimaki** [comment]
This looks like we have some issue with Node 11. If you have an option downgrade your node to 10 or below. One good tool for managing node version is [NVM](https://github.com/creationix/nvm). We are looking into it, but it might take few days until fix for latest Node reaches master.

**Comment by saikirubamj** [comment]
I have cleared all the error related to python manage.py build_resources

14 resources installed sucessfully...But still I facing below issue
![image](https://user-images.githubusercontent.com/48011458/53623192-630f1c00-3c22-11e9-9a7e-fb8b74b840af.png)

**Comment by chessbr** [comment]
Still having the issue? We couldn't reproduce this. Re-open the issue if you still need help. Thank you.
