### ISSUE TITLE
Order API does not expose line item taxes

### ISSUE THREAD

**Issue by jonovate** [shuup/shuup#1778]
For those countries where the Prices DO NOT Include Tax, it would be nice for the Order API to include some combination of item price, taxes, and/or taxful_price.

Main use case is when order contains Products that are Taxful and Taxless.

Thanks!

**Comment by chessbr** [comment]
API moved to https://github.com/shuup/shuup-rest-api.
If you still need assistance, please create an issue in the new repo. Thank you.
