### ISSUE TITLE
Xtheme inline script and style links injection won't work for non direct links

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1849]
When one want to add a custom JS or CSS with querystring using xtheme `add_resource`, it won't work because of this:

https://github.com/shuup/shuup/blob/master/shuup/xtheme/resources.py#L211-L215

It means the links MUST end with .js or .css which is not good for links like `https://example.org/script.js?v=0.3.1&token=bda3537a`

This we we should parse the URL and extract the file name and then check the extension correctly OR create custom resources for those.

**Comment by maximlion** [comment]
Can't we just check there if the URL contains ".js" in it?

**Comment by chessbr** [comment]
Fixed in https://github.com/shuup/shuup/pull/1928 and https://github.com/shuup/shuup/pull/1936
