### ISSUE TITLE
pip install shuup issue

### ISSUE THREAD

**Issue by mdnur89** [shuup/shuup#1910]
I am having an issue installling shuup via pip, it is completing but no folder is present in the working directory with a virtualenv activated. I'm on Manjaro32. Am i missing something?

**Comment by chessbr** [comment]
@mdnur89 Hi! If you are installing Shuup via PIP, the package is going to be placed on your python site-packages folder, not in local folder.

**Comment by mdnur89** [comment]
@chessbr Hehe, really...I've just realised last time i cloned the shuup repo and went on from there.. If i git clone vs using pip, its all the same right?

**Comment by chessbr** [comment]
@mdnur89 not the same. When you clone our repo you get the latest commit from master branch, which is the latest code but it can be a not released and stable version. We only upload final releases to PIP repo. You can also clone them if you want: https://github.com/shuup/shuup/releases
Just make sure to use the tag when cloning the repo and you should be safe. :smiley:

**Comment by mdnur89** [comment]
@chessbr Ohh, pip=stable and git clone=more or less bleeding edge.... I get it now... Git clone it is, simpler for me and much fun. Thank you man.

**Comment by chessbr** [comment]
Also, pip package has all static files already built, so you don't have to worry build those JS and CSS files manually.

**Comment by mdnur89** [comment]
@chessbr Really, fo realz man. Okay so can i move the shuup folder in the site-packages to another location and which ones do i move because i see 4 shuup folders.
