### ISSUE TITLE
Running tests causing error - django.core.exceptions.ImproperlyConfigured:

### ISSUE THREAD

**Issue by footlessbird** [shuup/shuup#1911]
After execution: py.test -v --nomigrations shuup_tests
error below occurs

<img width="1225" alt="error" src="https://user-images.githubusercontent.com/31249338/57832374-60758a80-776c-11e9-903d-826cd5943403.png">

in setup.cfg 
<img width="434" alt=" DJANGO_SETTINGS_MODULE" src="https://user-images.githubusercontent.com/31249338/57832542-bf3b0400-776c-11e9-96fe-61ec707945c3.png">

**Comment by chessbr** [comment]
Hi @footlessbird ! Can you run `pip list` and send us the result? Make sure Shuup is installed in your env using development mode: `pip install -e /path/to/shuup`

**Comment by footlessbird** [comment]
Hey thanks for response
I already did <code>pip install -e .</code>  
but did not do with **[everthing]** like below so:
<code>pip install -e . [everything]</code>
because of message - zsh: no matches found: .[everything]

this is the result of <code>pip list </code>
<img width="694" alt="pip list" src="https://user-images.githubusercontent.com/31249338/57889934-fc45db80-77ea-11e9-98ae-37b2fd20ff05.png">

**Comment by chessbr** [comment]
@footlessbird make sure to run like this: `pip install -e .[everything]` (without space)

**Comment by footlessbird** [comment]
<img width="610" alt="no matches found" src="https://user-images.githubusercontent.com/31249338/57903582-87db5e80-7823-11e9-91fc-9ffffb214253.png">

**Comment by tulimaki** [comment]
Hi @footlessbird,

pip install these:
```
beautifulsoup4==4.5.3
html5lib==0.999999999
mock==2.0.0
pytest-cache==1.0
pytest==3.0.6
pytest-cov==2.4.0
pytest-django==3.1.2
pytest-splinter==2.0.0
pytest-sugar==0.8.0
selenium==3.141.0
splinter==0.9.0
```

These are the testing requirements and you can also find these from tox.ini. We will look into this and maybe we should just add `requirements-tests.txt` to the repository to avoid confusion.
