### ISSUE TITLE
How To Develop Shuup

### ISSUE THREAD

**Issue by mikrokode** [shuup/shuup#1924]
Hi Friends,

I am C# programmer, usually develop Asp.net application. Recently, want to try something on python, I come across your apps, Shuup, amazing!!! I have some to ask you about the code.

For the whole folder code after I downloaded from github, I have totally no idea how is the ways to create this amazing e-commerce. I sure that you will encourage user to straight forward to use your e-commerce following the installation steps.

But, my interest is how to build a software of this kind from A to Z. I have gone through a few python django ebook, have fundamental in python. Can you share with us how you are going to develop this apps? For example, what IDE ? what package library ? What is the initial stage to design the whole architecture of this apps? How to start?

IT Enthusiast

**Comment by mikrokode** [comment]
Friends,

I hope you can share something with me, your apps is the most pretty after I found a bundle of open source.

Please!!!

**Comment by chessbr** [comment]
The platform was planned and built by senior experts that already had expertise with e-commerces. I think this is matter of experience :)
Thank you anyway.
