### ISSUE TITLE
Is shuup appropriate for service marketplaces like airbnb?

### ISSUE THREAD

**Issue by Sultan91** [shuup/shuup#1982]
With brief look into SHUUP, it seems like perfect choice regular marketplace of selling goods, carts etc. Is it possible to reconfigure (e.g. have some addons) to establish business logic of service marketplace, e.g. renting a bikes (two sided marketplace or multivendor) ?

Thanks in advance!)

**Comment by tulimaki** [comment]
@Sultan91 With open source version you would need to implemented the admin side where the vendors (`shuup.core.models.Supplier`) can manage the appartments. Basically custom product views and implementation for [this](https://github.com/shuup/shuup/blob/master/shuup/admin/supplier_provider.py) which indicates the currently active vendor for admin. Also you would need to customize the "order form" in the product detail for bookings. Airbnb like solution definitely should work with Shuup.

You can get more information around this by contacting support@shuup.com and/or request demo from our sales (shuup.com).
