### ISSUE TITLE
Markdown not cleaned in category product truncated description

### ISSUE THREAD

**Issue by jaywink** [shuup/shuup#204]
Product page description supports markdown (even though this is not evident when editing the product).

Category page does not render markdown (as it probably shouldn't), but also doesn't clean the markdown code away, see as follows:

![selection_161](https://cloud.githubusercontent.com/assets/1174866/10265587/0d6a2bf4-6a3f-11e5-8941-7f59de20c722.png)
![selection_160](https://cloud.githubusercontent.com/assets/1174866/10265588/100f736e-6a3f-11e5-8f34-d9bfb183f99b.png)

Shoop 1.2.0.post0.dev, current master head.

**Comment by juhakujala** [comment]
I would suggest that we provide another field for "description in product list" or something similar that supports only plain text. It can also be set to max chars so that it auto truncates itself without the template having to think about that.

**Comment by akx** [comment]
Thanks for the bug report. Tracking this as SHOOP-1619.
