### ISSUE TITLE
Page editing with html + markdown, inconsistency between preview vs saved page

### ISSUE THREAD

**Issue by jaywink** [shuup/shuup#208]
When editing in the full editor, the following works (markdown image embed inside html div):

![selection_166](https://cloud.githubusercontent.com/assets/1174866/10268977/b6f2bc80-6ad1-11e5-9729-2d06b77fcf02.png)

However, when saved it doesn't render the markdown image inside the div at all. Removing the div renders the image.

![selection_167](https://cloud.githubusercontent.com/assets/1174866/10268993/f0da4d32-6ad1-11e5-9f57-e3f79a6f8ddf.png)

**Comment by akx** [comment]
Thanks for the bug report. Tracking this as SHOOP-1618.
