### ISSUE TITLE
Bug: removing coupon button is not working (consistently) in cart page

### ISSUE THREAD

**Issue by mikkovedru** [shuup/shuup#2087]
1. Add a product to the cart.
2. Go to the cart.
3. Apply a working coupon.
4. Try to remove the coupon.

Problem: sometimes it's really hard to get a coupon removed. One click almost never does it, but if you spam the remove button, then it might happen after some non-similar number of clicks.

There are no errors in browser console.

If it is of any help, the coupon removal code has two JavaScript events linked to it:
```
function(evt) {
  var code = $(evt.target).data("code");
  if (code) {
    var data = {
      "command": "remove_campaign_code",
      "code": code
    };
    $.ajax({
      url: "",
      method: "POST",
      data: data,
      success: function(response) {
        if (response.ok) {
          location.reload();
        } else {
          alert("Invalid coupon code.")
        }
      },
      error: function() {
        alert("Error when removing coupon.")
      }
    });
  }
}
```

and
```
function(t) {
  return void 0 !== w && w.event.triggered !== t.type ? w.event.dispatch.apply(e, arguments) : void 0
}
```

**Comment by maximlion** [comment]
Fixed.
