### ISSUE TITLE
how to add a new shop?

### ISSUE THREAD

**Issue by AsimNet** [shuup/shuup#2138]
Hello,
thank you for your efforts.
I just installed Shuup, but I don't know how to add a new shop (like a marketplace)
https://www.shuup.com/multivendor-features/

thank you again!

**Comment by mikkovedru** [comment]
@AsimNet 
You need to enable this setting:
https://github.com/shuup/shuup/blob/master/shuup/core/settings.py#L92

At this point I would also like to tell/remind you of the developer documentation: https://shuup.readthedocs.io/en/latest/
