### ISSUE TITLE
Two sub-menus simultaneously shown in bold, instead of only one

### ISSUE THREAD

**Issue by mikkovedru** [shuup/shuup#2162]
If you go to `Campaigns` -> `Archived Product Discounts`, both the `Archived Product Discounts` and the `Product Discounts` sub-menus are shown in bold.
![image](https://user-images.githubusercontent.com/2521942/78931645-ec904f00-7aae-11ea-9c90-f002a2f011d6.png)

**Comment by chessbr** [comment]
Fixed here https://github.com/shuup/shuup/pull/2168
