### ISSUE TITLE
is shutdown shuup.com?

### ISSUE THREAD

**Issue by re4lfl0w** [shuup/shuup#2212]
I am not writing this on the issue bulletin board, but if you contact the homepage, there will be no answer.

I want to ask you to create a site, but I can't reach you.
How should I contact you?
When is the company suspended due to corona?
The company is suspended, but asks if the shuup.com code will continue to be modified.

from on Jan, 2020

Thank you.

**Comment by tulimaki** [comment]
Hi!

Thank you for your message. Shuup is definitely alive and well. Please forward your questions to support@shuup.com so our support team can answer your questions directly in your e-mail.

Thanks again!
