### ISSUE TITLE
Admin: new order product selection

### ISSUE THREAD

**Issue by wiltso** [shuup/shuup#2215]
When creating a new order in the admin panel, and under the "Order Contents" section if you search for a product with the search field. It will never find the product. The only thing it will display is "no results found".
![image](https://user-images.githubusercontent.com/17654252/86461828-41043d00-bd33-11ea-9d79-437ef1cfe72e.png)

**Comment by tulimaki** [comment]
Seems to work. Please provide steps how to reproduce.
