### ISSUE TITLE
Typo in pagination

### ISSUE THREAD

**Issue by fredcoff** [shuup/shuup#2272]
Pagination text is as below:
`Items %(start_index)d of %(end_index)d of %(count)d total`
e.g. Items 1 of 12 of 15

It should be:
`Items %(start_index)d to %(end_index)d of %(count)d total`
e.g. Items 1 to 12 of 15

**Comment by ruohola** [comment]
Feel free to submit a PR for this!

**Comment by ruohola** [comment]
Fixed in #2275
