### ISSUE TITLE
Remove United Kingdom / Great Britain from list of EU countries

### ISSUE THREAD

**Issue by klemmari1** [shuup/shuup#2340]
United Kingdom ("GB") is still part of European Union countries in the codebase.

Don't know all the affected functionalities but at least this line:
https://github.com/shuup/shuup/blob/master/shuup/core/models/_addresses.py#L33

Tags: Brexit

**Comment by ruohola** [comment]
A valid point, a PR would be welcome :)

I'm thinking also, should this field be changed to be `available_in_eu_countries`, as it now behaves that way: https://github.com/shuup/shuup/blob/237901c3d42b77e46548eb84d0e8807523223515/shuup/core/models/_service_behavior.py#L233-L234, maybe in an other PR.

**Comment by tulimaki** [comment]
@klemmari1 included in [v2.3.4](https://github.com/shuup/shuup/releases/tag/v2.3.4).
