### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by pythonyalfa** [shuup/shuup#2369]
I found the dockerfile after cloning shuup i ran the commands inside the dockerfile and though i havent got through the whole way, am i supposed to run this Dockerfile from the virtualenv i created for shuup ? Does it matter ?

**Comment by pythonyalfa** [comment]
So i ran these commands and finally was able to see a default page. I haven't gotten around to learning any docker which is killing me because obviously docker is handy for shuup. Though running the commands in the Dockerfile worked, I have a few questions before I go further. Why is it that I don't need to be in a virutal env to make it work? Is it because using pip to install shuup, installed it globally ? This is a screenshot of the default page 

![image](https://user-images.githubusercontent.com/26556488/105696395-7e433e80-5ec0-11eb-929c-792b4b972613.png)

am i good to go further? is there anything else i need to know or does anyone have any suggestions before i continue fiddling with shuup? 
I know django and python some but i want to start looking at proects which are popular already as my skill level isn't quite ready to turn my ideas into the next shuup thanks!!

**Comment by ruohola** [comment]
Not sure what is the question here.
