### ISSUE TITLE
Can not open Products and Categories pages.

### ISSUE THREAD

**Issue by jis0324** [shuup/shuup#2413]
![image](https://user-images.githubusercontent.com/59192045/111195060-3b354b80-8592-11eb-8d16-ce2921dad2bb.png)
![image](https://user-images.githubusercontent.com/59192045/111195102-48ead100-8592-11eb-850b-10a111347031.png)
![image](https://user-images.githubusercontent.com/59192045/111195281-79326f80-8592-11eb-9c4d-476c35e456ed.png)

**Comment by Jeffrca** [comment]
I am seeing the same error.  I believe it may have something to do with image handling.  When viewing the store, none of the sample categories or products show their images.  You can click on the missing product image and the image popup will open and display the image, but the product page does not.

You can "Edit Product In Admin", but still no images are visible.  A brief error note pops on screen saying "Error! Thumbnail Generation of image productxx.jpg failed:  Operation on closed Image".

**Comment by ankit25821** [comment]
I was getting same error because I clone [shuup](https://github.com/shuup/shuup) repo directly then I deleted it and created virtualenv and followed locally installation guide from [doc](https://shuup.readthedocs.io/en/latest/howto/getting_started.html#locally).
