### ISSUE TITLE
No option to add product variants

### ISSUE THREAD

**Issue by xpcoder123** [shuup/shuup#2415]
Ive installed Shuup on my localhost trying to explore how it works and if it will be the best for my next ecommerce website. My website will have lots of products variants. Ive watched a video on Shuup YouTube channel on how to add and manage variants but when I checked my dashboard I can't find that "Convert to variants parent"?
Check image below

![image](https://user-images.githubusercontent.com/44916136/111258249-fc83ad80-85f2-11eb-9be2-6219daedad1d.png)

Any idea why I don't have that?

**Comment by chessbr** [comment]
Hi @xpcoder123,
We created a new addon that we are working on, but it is currently only available through enterprise license at the moment.
