### ISSUE TITLE
Default products are not visible on home page.

### ISSUE THREAD

**Issue by ankit25821** [shuup/shuup#2620]
I've just followed locally installation [guide](https://shuup.readthedocs.io/en/latest/howto/getting_started.html#locally) and I've gone through this [post](https://chessbr.medium.com/creating-your-first-e-commerce-with-shuup-open-source-platform-part-1-72bb3bd32b23) also which is written by - ***Christian Hess***. In this when we start server and go to home page we can see some default products but in my case I can't see here is my admin products
![products](https://user-images.githubusercontent.com/67471937/154661874-3a038bce-7a49-4d53-9934-c1d7cc5bc651.png)
and this is how my home page looks 
![home page](https://user-images.githubusercontent.com/67471937/154662008-07e48c55-06e7-467e-8434-a9628ef2d2ee.png)
and my category page
![category](https://user-images.githubusercontent.com/67471937/154662074-7e71907a-b1b7-47d2-8266-818cf6d2fd12.png)

in my category page I can see category image but not products. Please help(:

**Comment by zhenguanyimin** [comment]
How do you fix this? I got the same proble @ankit25821
