### ISSUE TITLE
Product does not get added to basket if force_new_line = True

### ISSUE THREAD

**Issue by jaywink** [shuup/shuup#291]
I've spent a few hours debugging this but can't come up with a failing test to reproduce it, or find the right line where it goes wrong. But, I've got the following override class and basket spec set accordingly:

```
class ReservableBasket(BaseBasket):

    def add_product(self, supplier, shop, product, quantity, force_new_line=False, extra=None, parent_line=None):
        if not extra:
            extra = {}
        if self.request.POST.get("reservation_start", None):
            extra["reservation_start"] = self.request.POST.get("reservation_start")
            extra["adults"] = self.request.POST.get("adults", 1)
            extra["children"] = self.request.POST.get("children", 0)
        if product.type.identifier == "reservable":
            force_new_line = True
        return super(ReservableBasket, self).add_product(
            supplier, shop, product, quantity, force_new_line=force_new_line, extra=extra, parent_line=parent_line)
```

If `force_new_line` is not set to True, then everything works. But setting that to true causes the line not to be added to the basket at all.

After some debugging I ended up seeing that if it is set, then [this line](https://github.com/shoopio/shoop/blob/master/shoop/front/basket/objects.py#L230) is never hit. In the debugger I could see `self._data_lines` being empty, but not reliably enough, it seems to be not consistent. Also a lot of stuff happens after that. After some hours and trying to verify it with a test I'm not sure any more.

I tried the following'ish in a shell to think of a way how to replicate a test:

```
>>> from shoop.front.basket.objects import BaseBasket
>>> from django.test import RequestFactory
>>> from shoop.testing.factories import get_default_shop, create_product, get_default_supplier
>>> from shoop.testing.factories import ProductFactory
>>> from django.utils.translation import activate
>>> activate("en")
>>> request = RequestFactory().get("/")
>>> shop = get_default_shop()
>>> request.shop = shop
>>> request.session = {}
>>> basket = BaseBasket(request)
>>> product = ProductFactory()
>>> basket.add_product(supplier, shop, product, 1, force_new_line=True)
```

Just to let you know if you can figure out if this is a bug or not. For now I'll just override `BaseBasket._compare_line_for_addition` to return `False` for this custom product type.

**Comment by akx** [comment]
I wonder if this is related to https://github.com/shoopio/shoop/pull/330 :)

**Comment by jaywink** [comment]
Yep, seems to be fixed now, thanks!
