### ISSUE TITLE
Billing address - required fields

### ISSUE THREAD

**Issue by maltitco** [shuup/shuup#324]
The following fields should be as required when ordering:
- Phone
- Postal code

**Comment by akx** [comment]
They aren't necessarily required in all jurisdictions or for all merchants.

If you need to customize the checkout view, see the `SHOOP_CHECKOUT_VIEW_SPEC` configuration variable.

In particular, to do this,

* subclass `shoop.front.views.checkout.DefaultCheckoutView` (let's call this `CustomCheckoutView`)
* subclass `shoop.front.checkout.addresses:AddressesPhase` (let's call this `CustomAddressesPhase`)
* in the checkout view subclass, override `phase_specs` to replace the addresses phase with your custom one
* in the address phase subclass,
** either override `address_form_class` entirely with a form class of your own
** or override `get_form` to add the requisite `required` flags to the required fields -- like this:
```python
form = super(...).get_form(...)
form.forms["billing"].fields["phone"].required = True
form.forms["billing"].fields["postal_code"].required = True
return form
```
* set `SHOOP_CHECKOUT_VIEW_SPEC` to `CustomCheckoutView`'s spec string

HTH. :)

**Comment by maltitco** [comment]
Thank you for your answer.
You could add this information to documentation.
