### ISSUE TITLE
How add more shop in admin panel

### ISSUE THREAD

**Issue by molaaaa** [shuup/shuup#361]
With regard to the following link, the latest version of shoop supports multisite, but how should I add more shop to shoop_workbench sample?

https://community.shoop.io/forums/t-21/multisite-support/

**Comment by mwanjajoel** [comment]
Simply go to Menu>System>Shops. click on the add new button in the top right corner. This applies to Shuup 4.0

**Comment by maris-teivans** [comment]
I have this menu in shuup: Quicklinks/Orders/Products/Contacts/Campaigns/Content/Reports/Shops/Addons/Settings. When I go to the section Shops->Shops, there is a list of all shops(just one now), but I don't see any add new button anywhere there. Am I doing something wrong or maybe I don't have the real version?
[https://gyazo.com/be33d10601a74a53674dffa4597b3769](https://gyazo.com/be33d10601a74a53674dffa4597b3769)
