### ISSUE TITLE
[enhancement] Consider different types of products

### ISSUE THREAD

**Issue by 1905410** [shuup/shuup#376]
As I can see, current Shoop implantation presume that all products are physical, but what about, for example, digital products?

Even the main Product model declare required [physical dimensions](https://github.com/shoopio/shoop/blob/master/shoop/core/models/_products.py#L195). Wouldn't it be more reasonable to develop Shoop with keeping in mind possibility of different product types?

For example, in the case mentioned above, you can add to the Product model type mixins (like ProductPhysical, ProductDigital, ProductVariationChild, etc) and mark type specific fields with `null=True, blank=True`. Besides, it will allow you to keep the Product model more clear, by separating specific type methods from it.

_sorry for my grammar_ (._.)

**Comment by akx** [comment]
Even if those physical dimensions are ostensibly required, they can be all zeroes (which makes sense for a digital product, doesn't it? :) ).

Other than that there's no real presumption that products are physical.

**Comment by 1905410** [comment]
> Even if those physical dimensions are ostensibly required, they can be all zeroes

A half year ago that was just quite annoying to set 5-6 fields to zero on every new created product. But in the later admin panel updates it has been fixed so now it is more or less ok. Of course would be cute to make the physical dimensions to disappear all tougher on digital products, but it is not critical.

I suppose this one could be closed.
