### ISSUE TITLE
Failed to build shoop

### ISSUE THREAD

**Issue by manish2409** [shuup/shuup#45]
Hi 
I tried to install shoop in my linuxmint 17.1.
I used the following steps.
1) Install necessities git, npm, nodejs, virtualenv
2) created a virtualenv named shoop and installed django in it
3) installed shoop from shoop-master/
It gives me this error:

Complete log...

(shoop)manish@manish-vm ~/Projects/shoop/shoop_demo $ pip install /home/manish/Downloads/shoop-master/
Processing /home/manish/Downloads/shoop-master
  Requirement already satisfied (use --upgrade to upgrade): shoop==1.1.0.post0.dev0 from file:///home/manish/Downloads/shoop-master in /home/manish/Projects/shoop/lib/python2.7/site-packages/shoop-1.1.0.post0.dev0-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): Babel==1.3 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): Django==1.8.2 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-bootstrap3==6.1.0 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-countries==3.3 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-enumfields==0.7.3 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-filer==0.9.11 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-jinja==1.4.1 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-mptt==0.7.4 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-parler==1.4 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-polymorphic==0.7.1 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-registration-redux==1.2 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): django-timezone-field==1.2 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): djangorestframework==3.1.3 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): factory-boy==2.5.2 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): fake-factory==0.5.2 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): jsonfield==1.0.3 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): Markdown==2.6.2 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): pytz==2015.4 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): six==1.9.0 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): enum34==1.0.4 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): Unidecode>=0.04 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from django-filer==0.9.11->shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): easy-thumbnails>=1.0 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from django-filer==0.9.11->shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): jinja2>=2.5 in /home/manish/Projects/shoop/lib/python2.7/site-packages (from django-jinja==1.4.1->shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/manish/Projects/shoop/lib/python2.7/site-packages (from django-polymorphic==0.7.1->shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): pillow in /home/manish/Projects/shoop/lib/python2.7/site-packages (from easy-thumbnails>=1.0->django-filer==0.9.11->shoop==1.1.0.post0.dev0)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/manish/Projects/shoop/lib/python2.7/site-packages (from jinja2>=2.5->django-jinja==1.4.1->shoop==1.1.0.post0.dev0)
Building wheels for collected packages: shoop
  Running setup.py bdist_wheel for shoop
  Complete output from command /home/manish/Projects/shoop/bin/python -c "import setuptools;__file__='/tmp/pip-byELhk-build/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpPVwXh4pip-wheel-:
  /home/manish/Projects/shoop/local/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '1.1.0.post0.dev' to '1.1.0.post0.dev0'
    normalized_version,
  running bdist_wheel
  running build
  running build_production_resources
  npm ERR! Failed to parse json
  npm ERR! Unexpected token U
  npm ERR! File: /tmp/pip-byELhk-build/shoop/notify/package.json
  npm ERR! Failed to parse package.json data.
  npm ERR! package.json must be actual JSON, not just JavaScript.
  npm ERR!
  npm ERR! This is not a bug in npm.
  npm ERR! Tell the package author to fix their package.json file. JSON.parse
  
  npm ERR! System Linux 3.13.0-37-generic
  npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
  npm ERR! cwd /tmp/pip-byELhk-build/shoop/notify
  npm ERR! node -v v0.10.25
  npm ERR! npm -v 1.3.10
  npm ERR! file /tmp/pip-byELhk-build/shoop/notify/package.json
  npm ERR! code EJSONPARSE
  npm ERR!
  npm ERR! Additional logging details can be found in:
  npm ERR!     /tmp/pip-byELhk-build/shoop/notify/npm-debug.log
  npm ERR! not ok code 0
  *** (1/2) Building: ./shoop/notify
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-byELhk-build/setup.py", line 138, in <module>
      cmdclass=utils.COMMANDS,
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/manish/Projects/shoop/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "shoop_setup_utils/commands.py", line 75, in run
      resource_building.build_resources(opts)
    File "shoop_setup_utils/resource_building.py", line 46, in build_resources
      builder.build_all()
    File "shoop_setup_utils/resource_building.py", line 67, in build_all
      self.build_dirs(package_json_dirs)
    File "shoop_setup_utils/resource_building.py", line 79, in build_dirs
      self.build(dir)
    File "shoop_setup_utils/resource_building.py", line 87, in build
      self._run_build(dir)
    File "shoop_setup_utils/resource_building.py", line 96, in _run_build
      subprocess.check_call(self.command, cwd=dir, env=self.env, shell=shell)
    File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for shoop
Failed to build shoop

**Comment by juhakujala** [comment]
Unfortunately I can't reproduce your issue. Do you have the latest shoop zip from git?

You could also try to run ``python setup.py build_resources`` at your shoop-master directory. It may give us a better error message if it fails to build.

**Comment by manish2409** [comment]
running python setup.py build_resources gave me this:

/home/manish/Projects/shoop/local/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '1.1.0.post0.dev' to '1.1.0.post0.dev0'
  normalized_version,
running build_resources

**Comment by manish2409** [comment]
can you tell me how to check if shoop has been installed correctly?

**Comment by tulimaki** [comment]
Also from previous traceback it looks like installing wheel is failing. If python setup.py build_recources inside your shoop-master directory runs without errors there might be some problems with your pip. You can try updating your pip (pip install -U pip) also from wheel documentation it seems that setuptools >=0.8.0 is required. Also you can try installing wheel separately before installing whole shoop (this should not be needed).

To check if shoop is installed correctly your pip install should run without errors. Also shoop should be visible in your pip freeze. If shoop is not installed correctly you should get some errors while setting up your django project with shoop.

**Comment by suutari** [comment]
Pip copies the Shoop sources from the Git checkout to /tmp for building. Maybe it has failed to copy some file correctly. Check that the file `/tmp/pip-byELhk-build/shoop/notify/package.json` (mentioned in the error message) seems correct. You may compare it to `/home/manish/Downloads/shoop-master/shoop/notify/package.json` and https://raw.githubusercontent.com/shoopio/shoop/master/shoop/notify/package.json. Do you have enough disk space in /tmp btw? (run `df -h /tmp`)
