### ISSUE TITLE
Just set up shoop

### ISSUE THREAD

**Issue by faddat** [shuup/shuup#46]
Can I add/delete categories and products from the GUI?  Logged into admin/admin account.  Thanks!

**Comment by juhakujala** [comment]
If you have your own Shoop instance installed just go to yoursite.com/sa/ to get to the admin panel.

Click the menu button (top left corner) and under products you can find categories and products which you can then modify to your needs.

**Comment by akx** [comment]
@faddat Did you get things up and running? :)
