### ISSUE TITLE
Migration woes with post 3.0.0 dev version

### ISSUE THREAD

**Issue by jaywink** [shuup/shuup#554]
I have a site running ~3.0.0. Locally trying to see whether upgrading to (almost) current development head would make sense and I'm having problems applying the migrations to a locally copied database.

The problem is that Shuup is mixing `RunPython` data migrations and table alters in the same migration. Django doesn't handle it well if after `RunPython` there are schema altering changes done. PostgreSQL raises for me for example with `core.0020_services_and_methods`:

    django.db.utils.OperationalError: cannot ALTER TABLE "shoop_paymentmethod" because it has pending trigger events

Commenting out the `RunPython` and the (dependent on those) following alters passes that one, but the same crash comes in `simple_cms.0004_add_parents`. There could be other migrations too, I stopped here.

There is some discussion regarding this in [a Django ticket](https://code.djangoproject.com/ticket/24630).

[Docs on RunPython](https://docs.djangoproject.com/en/1.8/ref/migration-operations/#runpython) explicitly say not to mix data and schema migrations:

> On databases that do support DDL transactions (SQLite and PostgreSQL), RunPython operations do not have any transactions automatically added besides the transactions created for each migration (the atomic parameter has no effect on these databases). Thus, on PostgreSQL, for example, you should avoid combining schema changes and RunPython operations in the same migration or you may hit errors like OperationalError: cannot ALTER TABLE "mytable" because it has pending trigger events.

Would suggest cleaning up any post-3.0.0 migrations before a release or otherwise any PostgreSQL users are going to have a hell of a time updating.

**Comment by suutari-ai** [comment]
@jaywink: Thanks for reporting this. Tracking this as SHUUP-2882 internally.

**Comment by suutari-ai** [comment]
Sorry, but this would need many changes to migrations which we don't have time to do before the next release.
