### ISSUE TITLE
"Add new image" in product don't work

### ISSUE THREAD

**Issue by Boquete** [shuup/shuup#621]
Button **Add New Image** instead of adding image in **Product Image** is adding field in **Product Media**.

**Comment by Pikkupomo** [comment]
@Boquete Thanks for reporting this. I labeled this as a bug and we will look into this.

**Comment by gurch101** [comment]
This was fixed in commit e70382f87c75f3c8ba1a5919f2a3640be10aedbf. SHUUP 0.4.1+ should have the updates. Thanks!
