### ISSUE TITLE
UndefinedError at / 'django.core.handlers.wsgi.WSGIRequest object' has no attribute 'shop'

### ISSUE THREAD

**Issue by mwanjajoel** [shuup/shuup#622]
Got that error when the front end tried to load

**Comment by Pikkupomo** [comment]
To run Shuup you have to have a `Shop` created. Have you tried running the management command `python -m shuup_workbench shuup_init` which creates a shop.

**Comment by tulimaki** [comment]
Ín case the previous didn't work you probably are missing `shuup.front.middleware.ShuupFrontMiddleware` from your project settings. Please check [this](https://github.com/shuup/shuup/blob/master/shuup_workbench/settings/base_settings.py) for default project settings.
