### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by spookylukey** [shuup/shuup#74]
AGPL seems a really strange choice for a Python ecommerce project. Some people would interpret GPL to mean that any website using shoop must provide all its source code under the same license, which is not going to be attractive to many ecommerce sites. For a Django app designed for non-profits, it might make more sense, but ecommerce sites are almost always going to be commercial.

When GPL meets Python, things get more complex:

https://jacobian.org/writing/gpl-questions/
http://lukeplant.me.uk/blog/posts/python-and-copyright/

The current license page leaves everything as clear as mud - https://www.shoop.io/shoop/license/ - but a clarification there still wouldn't be a substitute for a legal consensus on what the use of AGPL does to Python libraries and projects using them.

**Comment by atifsyedali** [comment]
Honestly, this project would gain a lot of traction if it was not licensed under the AGPL (or GPL for that matter). The fact that any addons written must also be AGPL-compatible is really preventing many of us from contributing.

If there are financial concerns here, Shuup can always setup a marketplace of addons where they would be able to take a cut of the sellers of the addons (similar to Magento?).

I strongly urge the authors here to reconsider the licensing scheme. An MIT or Apache license would be ideal to foster a Shuup community.

**Comment by gomnuts** [comment]
Thank you for your messages @atifsyedali and @spookylukey ! You both are right, AGPL is a pretty heavy license for the Open Source community. 

SO GOOD NEWS!
We are opening the Shuup Marketplace by the end of August 2016, as well as our JIRA backlog (tickets and tasks) for the community.
At the same time, we are making changes to our license to make it easier for the community to contribute. Both Apache and MIT licenses are being highly considered. We will be announcing these decisions shortly. If you have any more recommendations on selecting the best license, please don't hesitate to contact me directly at tomi@shuup.com. Thanks guys!

Please stay in touch for these releases by the end of August 2016!

Best,
Tomi Alapaattikoski
Shuup
Founder and CEO

**Comment by atifsyedali** [comment]
That's great news! Any chance that you could make the licensing changes sooner?

**Comment by orion-v** [comment]
Any news about the license change? Thank you!

**Comment by chessbr** [comment]
Any news?
