### ISSUE TITLE
Products page not working

### ISSUE THREAD

**Issue by arnold-iakab** [shuup/shuup#756]
Hi, 

I found out that the Products page is not working when configuring a shuup project from scratch using the settings configuration of the workbench project. When I run the workbench project, the page is working, but with my own project, I get the following error: "shuup_testing/products: Not found".

Now I looked into this through the source code and when the "/xtheme/products" link is accessed, a function that needs to return the products view is returning None. 

The function in cause is "get_view" and is defined in "_theme.py", which exists in "shuup\xtheme\".

I modified the function, adding these two lines and now the Products page is working:

import shuup.front.themes.views as views
return getattr(views, view_name, None)

I hope this is helpful.

**Comment by tulimaki** [comment]
Thanks! In case you are using some different theam then Classic Gray with default templates then the `get_view`-method needs to contain those `shuup.front.themes.views`.
