### ISSUE TITLE
"No Shop!" error

### ISSUE THREAD

**Issue by srinivasgumdelli** [shuup/shuup#816]
I'm getting the "No Shop!" error when trying to run the server. Tried debugging it and 
`print Shop.objects.first()` (https://github.com/shuup/shuup/blob/master/shuup/front/middleware.py#L77) returns `None`. 

Can anyone please help me with the issue?

**Comment by gurch101** [comment]
Please run `python.manage.py shuup_init`. If you plan on doing Shuup development, you could run `python -m shuup_workbench shuup_populate_mock --with-superuser=admin` as an alternative.

See the docs for additional info: http://shuup.readthedocs.io/en/latest/getting_started_dev.html
