### ISSUE TITLE
shuup setup error under python 3.4.4+mysql 5.7+ shuup-0.5.0-py2.py3-none-any.whl

### ISSUE THREAD

**Issue by aaron8tang** [shuup/shuup#829]
MySQL connector version is: 2.1.3
django engine is: 'ENGINE': 'mysql.connector.django',
when i ran :
python manage.py migrate

error encountered:

Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying filer.0001_initial... OK
  Applying filer.0002_auto_20150606_2003... OK
  Applying shuup.0001_initial... OK
  Applying shuup.0002_rounding...Traceback (most recent call last):
  File "d:\devhome\python3\lib\site-packages\mysql\connector\django\base.py", li
ne 177, in _execute_wrapper
    return method(query, args)
  File "d:\devhome\python3\lib\site-packages\mysql\connector\cursor.py", line 51
5, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "d:\devhome\python3\lib\site-packages\mysql\connector\connection.py", lin
e 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "d:\devhome\python3\lib\site-packages\mysql\connector\connection.py", lin
e 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1091 (42000): Can't DROP 'PRIMARY'; che
ck that column/key exists

**Comment by tulimaki** [comment]
Could you try INNODB in your MySQL options? Something like this:

```
setup.DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "shuup",
            "USER": "root",
            "PASSWORD": "root",
            "HOST": "",
            "PORT": "",
            "OPTIONS": {
                "init_command": "SET storage_engine=INNODB;",
            }
        }
    }
```

**Comment by aaron8tang** [comment]
I've changed the ENGINE config from 
'ENGINE': 'mysql.connector.django',
to
'ENGINE': 'django.db.backends.mysql'
it's OK now.
