### ISSUE TITLE
How to enable SHUUP subsite? like www.web.com/store/

### ISSUE THREAD

**Issue by greenmughal** [shuup/shuup#859]
I had partial success of enabling /store level **subsite** of shuup but its not fully functional as some of the ajax and other things are still trying to access root url.

Please advise the proper way to enable **subsite** in shuup.

**Comment by gurch101** [comment]
This should be possible through your webserver config using aliases/rewrite rules. In nginx, you can do something like this:
```
location /store {
            include /etc/nginx/uwsgi_params;
            uwsgi_pass django;

            uwsgi_param Host $host;
            uwsgi_param X-Real-IP $remote_addr;
            uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
            uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
}
```

**Comment by greenmughal** [comment]
Thanks man
