### ISSUE TITLE
Shuup unable to capture real ip through Nginx+Gunicorn(sockets)

### ISSUE THREAD

**Issue by greenmughal** [shuup/shuup#862]
I see in source code following is hard coded 

> self.request.META.get("REMOTE_ADDR"),

While only HTTP_REMOTE_ADDR has the real ip address. Is there a way to copy HTTP_REMOTE_ADDR to REMOTE_ADDR without modifying SHUUP code.
Also future versions of Shuup should make this header variable configruable.

**Comment by chessbr** [comment]
Hello there!
I had the same problem and I asked this question in their gitter. I proposed the usage of the `ipware` project to get the real ip address from the end user. Well, they answered me with a better solution: **a custom middleware**. Here what I've done:

```python
from django.conf import settings
from ipware.ip import get_ip, get_real_ip

class IpwareMiddleware(object):
    def __init__(self):
        self.debug = settings.DEBUG

    def process_request(self, request):
        if self.debug:
            request.META['REMOTE_ADDR'] = get_ip(request)
        else:
            request.META['REMOTE_ADDR'] = get_real_ip(request)
```

This way, I overwrite the REMOTE_ADDR with the correct IP address.
Then, put this middleware before the `ShuupFrontMiddleware` in settings:

```python
    ...
    'shuup_marleys.middleware.IpwareMiddleware',
    'shuup.front.middleware.ProblemMiddleware',
    'shuup.front.middleware.ShuupFrontMiddleware'
    ...
```

and your are good to go :)

**Comment by greenmughal** [comment]
Thanks man, appreciated.
