### ISSUE TITLE
My shuup based website is not showing up in google search results at all...

### ISSUE THREAD

**Issue by greenmughal** [shuup/shuup#870]
Domain Godaddy
server AWS
Nginx+Guncorn+SHUUP

Is it normal, i just launched website few days ago but its not showing anything related to website.
I also added it to google web search console.

Any suggestions?
Should I implement django's sitemap.xml?

**Comment by JoaRiski** [comment]
I can't comment on your actual question, but this seems like something that could find better help over at https://community.shuup.com/forums/

Good luck!
