### ISSUE TITLE
Virtualenv in Dockerfile breaks build_messages

### ISSUE THREAD

**Issue by kvdveer** [shuup/shuup#875]
Inside the Dockerfile, a virtualenv is created. This virtualenv is then used by using `/var/www/shuup/venv/bin/python` as the python executable. This seems incorrect to me, as most of the virtualenv's environment is missing. Specifically, the `$PATH` environment variable is not updated to include the virtualenv's `bin` dir. This omission breaks `build_messages`, which is run during setup. `build_messages` uses `django-admin` from the virtualenv, which can't be found in the OS' `PATH`

I can think of 2 solutions:
1. don't use virtualenvs in the docker image.
2. amend the $PATH variable to include the virtualenv's path

I'm willing to write/test the patch once a choice has been made.

**Comment by kvdveer** [comment]
A third option would be to remove the Dockerfile. The current file is not functional, which gives a bad first impression to the docker-inclined folks out there (that includes me). If this option is not chosen, I would like to add a travis task to verify the Dockerfile can actually be build.

**Comment by tulimaki** [comment]
Yeah I think the problematic thing here is the npm build. Even if it went through, the build will take some time and it also seems to get stuck pretty easily.

As a fourth option I would suggest to build the image from latest release wheel. That would make things fast and more reliable.

I am happy to accept this change to the Dockerfile. Also with good reasoning I can accept other solutions too, I don't see any need for the virtualenv so maybe the option 1 could be ok.

In case you are not interested to continue with this we will probably do the wheel change later, but for now fixing this is not highest priority for us.

**Comment by lupa18** [comment]
+1
