### ISSUE TITLE
what happened with the repo, only 1 commit? 

### ISSUE THREAD

**Issue by hbakhtiyor** [shuup/shuup#953]

**Comment by EduardoZepeda** [comment]
I want to know too. If I remember correctly shuup was in ver 3.0 a few months ago, today I checked again and shuup is ver 0.5

**Comment by paolodina** [comment]
> We flattened the repository few weeks ago in preparation of our 1.0 launch which will include everything again.

https://gitter.im/shuup/shuup?at=584afbe8c29531ac5d41a43b
