### ISSUE TITLE
Error installing shuup

### ISSUE THREAD

**Issue by vikrantrathore** [shuup/shuup#988]
The latest version 1.1.0 gives following error while installing:
This error pops up while running "python setup.py build_resources"
Most likely error due to NPM or node version issue:

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Users/vikrantrathore/projects/shupp_test/shuup/admin/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! shuup.admin@1.0.0 build: `npm i && gulp bower && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shuup.admin@1.0.0 build script 'npm i && gulp bower && gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shuup.admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && gulp bower && gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shuup.admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls shuup.admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by strycore** [comment]
Shuup 1.1.0 is only compatible with Node 6.x / npm 3.x, you can downgrade with nvm to use a compatible version. Shuup 1.2.0 will contain a fix and will be compatible with the latest version of Node and NPM.

**Comment by talaviram** [comment]
I'm seeing this with latest master tip (#e02c2e)

macOS 10.12.3 / npm 4.4.4 / node 7.7.3
