### ISSUE TITLE
Product packages: A package parent refers to products, the Widget lets you select ShopProducts

### ISSUE THREAD

**Issue by l0rn** [shuup/shuup#989]
I guess it's wanted that you select ShopProducts - but after selections I get an error for the admin

DoesNotExist at /sa/products/11/package/
Product matching query does not exist.

What happens is that it tries to find a Product with the ID of the just selected ShopProduct.

Steps to reproduce:

Create two new products
Convert the first you created to a package parent
Select the second you created as a package child with the Browse button
Click on save
The described error occurs

Affects:
master as of 29cd1226dadeff6c7dd86c3b309da9271db9a089
release 1.1.0

**Comment by tulimaki** [comment]
Thanks for the report. There is definitely issue in package/variation product views. The browser picks shop product id and tries to get product based on that.

This issue is on our board and fix for this will be available at the master soon.
